// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cdc.proto

package cdcpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_UNSENT      MessageStatus = 2
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_UNSENT",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENT":        1,
		"MESSAGE_STATUS_UNSENT":      2,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cdc_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_cdc_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{0}
}

// ... messages ...
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_cdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{0}
}

type GetConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           *AppConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	AvailableSources []string               `protobuf:"bytes,2,rep,name=available_sources,json=availableSources,proto3" json:"available_sources,omitempty"`
	AvailableSinks   []string               `protobuf:"bytes,3,rep,name=available_sinks,json=availableSinks,proto3" json:"available_sinks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_cdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *AppConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetAvailableSources() []string {
	if x != nil {
		return x.AvailableSources
	}
	return nil
}

func (x *GetConfigResponse) GetAvailableSinks() []string {
	if x != nil {
		return x.AvailableSinks
	}
	return nil
}

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogMode       string                 `protobuf:"bytes,2,opt,name=log_mode,json=logMode,proto3" json:"log_mode,omitempty"`
	Sources       []*SourceConfig        `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Sinks         []*SinkConfig          `protobuf:"bytes,4,rep,name=sinks,proto3" json:"sinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_cdc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{2}
}

func (x *AppConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppConfig) GetLogMode() string {
	if x != nil {
		return x.LogMode
	}
	return ""
}

func (x *AppConfig) GetSources() []*SourceConfig {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AppConfig) GetSinks() []*SinkConfig {
	if x != nil {
		return x.Sinks
	}
	return nil
}

type SourceConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host            string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port            int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username        *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password        *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Database        string                 `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	Tables          []string               `protobuf:"bytes,7,rep,name=tables,proto3" json:"tables,omitempty"`
	SlotName        *string                `protobuf:"bytes,8,opt,name=slot_name,json=slotName,proto3,oneof" json:"slot_name,omitempty"`
	PublicationName *string                `protobuf:"bytes,9,opt,name=publication_name,json=publicationName,proto3,oneof" json:"publication_name,omitempty"`
	InstanceId      *string                `protobuf:"bytes,10,opt,name=instance_id,json=instanceId,proto3,oneof" json:"instance_id,omitempty"`
	Name            *string                `protobuf:"bytes,11,opt,name=name,proto3,oneof" json:"name,omitempty"` // Display name
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_cdc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{3}
}

func (x *SourceConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SourceConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SourceConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SourceConfig) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *SourceConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SourceConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SourceConfig) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *SourceConfig) GetSlotName() string {
	if x != nil && x.SlotName != nil {
		return *x.SlotName
	}
	return ""
}

func (x *SourceConfig) GetPublicationName() string {
	if x != nil && x.PublicationName != nil {
		return *x.PublicationName
	}
	return ""
}

func (x *SourceConfig) GetInstanceId() string {
	if x != nil && x.InstanceId != nil {
		return *x.InstanceId
	}
	return ""
}

func (x *SourceConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type SinkConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url             []string               `protobuf:"bytes,2,rep,name=url,proto3" json:"url,omitempty"`
	Username        *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password        *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	IndexPrefix     *string                `protobuf:"bytes,5,opt,name=index_prefix,json=indexPrefix,proto3,oneof" json:"index_prefix,omitempty"`
	Index           *string                `protobuf:"bytes,6,opt,name=index,proto3,oneof" json:"index,omitempty"`
	IndexMapping    map[string]string      `protobuf:"bytes,7,rep,name=index_mapping,json=indexMapping,proto3" json:"index_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BatchSize       *int32                 `protobuf:"varint,8,opt,name=batch_size,json=batchSize,proto3,oneof" json:"batch_size,omitempty"`
	FlushIntervalMs *int32                 `protobuf:"varint,9,opt,name=flush_interval_ms,json=flushIntervalMs,proto3,oneof" json:"flush_interval_ms,omitempty"`
	MaxRetries      *int32                 `protobuf:"varint,10,opt,name=max_retries,json=maxRetries,proto3,oneof" json:"max_retries,omitempty"`
	RetryBaseMs     *int32                 `protobuf:"varint,11,opt,name=retry_base_ms,json=retryBaseMs,proto3,oneof" json:"retry_base_ms,omitempty"`
	ApiKey          *string                `protobuf:"bytes,12,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`
	InstanceId      *string                `protobuf:"bytes,13,opt,name=instance_id,json=instanceId,proto3,oneof" json:"instance_id,omitempty"` // Unique ID for sink
	Name            *string                `protobuf:"bytes,14,opt,name=name,proto3,oneof" json:"name,omitempty"`                               // Display name
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SinkConfig) Reset() {
	*x = SinkConfig{}
	mi := &file_cdc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkConfig) ProtoMessage() {}

func (x *SinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkConfig.ProtoReflect.Descriptor instead.
func (*SinkConfig) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{4}
}

func (x *SinkConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SinkConfig) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *SinkConfig) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *SinkConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SinkConfig) GetIndexPrefix() string {
	if x != nil && x.IndexPrefix != nil {
		return *x.IndexPrefix
	}
	return ""
}

func (x *SinkConfig) GetIndex() string {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return ""
}

func (x *SinkConfig) GetIndexMapping() map[string]string {
	if x != nil {
		return x.IndexMapping
	}
	return nil
}

func (x *SinkConfig) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *SinkConfig) GetFlushIntervalMs() int32 {
	if x != nil && x.FlushIntervalMs != nil {
		return *x.FlushIntervalMs
	}
	return 0
}

func (x *SinkConfig) GetMaxRetries() int32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

func (x *SinkConfig) GetRetryBaseMs() int32 {
	if x != nil && x.RetryBaseMs != nil {
		return *x.RetryBaseMs
	}
	return 0
}

func (x *SinkConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *SinkConfig) GetInstanceId() string {
	if x != nil && x.InstanceId != nil {
		return *x.InstanceId
	}
	return ""
}

func (x *SinkConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Dynamic Operations
type AddSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *SourceConfig          `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceRequest) Reset() {
	*x = AddSourceRequest{}
	mi := &file_cdc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceRequest) ProtoMessage() {}

func (x *AddSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceRequest.ProtoReflect.Descriptor instead.
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{5}
}

func (x *AddSourceRequest) GetSource() *SourceConfig {
	if x != nil {
		return x.Source
	}
	return nil
}

type AddSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceResponse) Reset() {
	*x = AddSourceResponse{}
	mi := &file_cdc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceResponse) ProtoMessage() {}

func (x *AddSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceResponse.ProtoReflect.Descriptor instead.
func (*AddSourceResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{6}
}

func (x *AddSourceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type RemoveSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceRequest) Reset() {
	*x = RemoveSourceRequest{}
	mi := &file_cdc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceRequest) ProtoMessage() {}

func (x *RemoveSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSourceRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSourceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type RemoveSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceResponse) Reset() {
	*x = RemoveSourceResponse{}
	mi := &file_cdc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceResponse) ProtoMessage() {}

func (x *RemoveSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceResponse.ProtoReflect.Descriptor instead.
func (*RemoveSourceResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveSourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddSinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sink          *SinkConfig            `protobuf:"bytes,1,opt,name=sink,proto3" json:"sink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSinkRequest) Reset() {
	*x = AddSinkRequest{}
	mi := &file_cdc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSinkRequest) ProtoMessage() {}

func (x *AddSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSinkRequest.ProtoReflect.Descriptor instead.
func (*AddSinkRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{9}
}

func (x *AddSinkRequest) GetSink() *SinkConfig {
	if x != nil {
		return x.Sink
	}
	return nil
}

type AddSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSinkResponse) Reset() {
	*x = AddSinkResponse{}
	mi := &file_cdc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSinkResponse) ProtoMessage() {}

func (x *AddSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSinkResponse.ProtoReflect.Descriptor instead.
func (*AddSinkResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{10}
}

func (x *AddSinkResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type RemoveSinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSinkRequest) Reset() {
	*x = RemoveSinkRequest{}
	mi := &file_cdc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSinkRequest) ProtoMessage() {}

func (x *RemoveSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveSinkRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveSinkRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type RemoveSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSinkResponse) Reset() {
	*x = RemoveSinkResponse{}
	mi := &file_cdc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSinkResponse) ProtoMessage() {}

func (x *RemoveSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSinkResponse.ProtoReflect.Descriptor instead.
func (*RemoveSinkResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveSinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_cdc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{13}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"` // seconds since start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_cdc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_cdc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{15}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SourceStats   map[string]*ComponentStats `protobuf:"bytes,1,rep,name=source_stats,json=sourceStats,proto3" json:"source_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SinkStats     map[string]*ComponentStats `protobuf:"bytes,2,rep,name=sink_stats,json=sinkStats,proto3" json:"sink_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_cdc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsResponse) GetSourceStats() map[string]*ComponentStats {
	if x != nil {
		return x.SourceStats
	}
	return nil
}

func (x *GetStatsResponse) GetSinkStats() map[string]*ComponentStats {
	if x != nil {
		return x.SinkStats
	}
	return nil
}

type ComponentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  uint64                 `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  uint64                 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	LastError     string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentStats) Reset() {
	*x = ComponentStats{}
	mi := &file_cdc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStats) ProtoMessage() {}

func (x *ComponentStats) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStats.ProtoReflect.Descriptor instead.
func (*ComponentStats) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentStats) GetSuccessCount() uint64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ComponentStats) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ComponentStats) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Advanced Explorer
type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MessageStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=cdc.v1.MessageStatus" json:"status,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Stream sequence start
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SourceId      *string                `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_cdc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{18}
}

func (x *ListMessagesRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ListMessagesRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageItem         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_cdc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{19}
}

func (x *ListMessagesResponse) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_cdc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{20}
}

func (x *MessageItem) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MessageItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MessageItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetConsumerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerInfoRequest) Reset() {
	*x = GetConsumerInfoRequest{}
	mi := &file_cdc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerInfoRequest) ProtoMessage() {}

func (x *GetConsumerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConsumerInfoRequest) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{21}
}

func (x *GetConsumerInfoRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type GetConsumerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckFloor      uint64                 `protobuf:"varint,1,opt,name=ack_floor,json=ackFloor,proto3" json:"ack_floor,omitempty"` // Highest sequence fully acknowledged
	PendingCount  uint64                 `protobuf:"varint,2,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerInfoResponse) Reset() {
	*x = GetConsumerInfoResponse{}
	mi := &file_cdc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerInfoResponse) ProtoMessage() {}

func (x *GetConsumerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConsumerInfoResponse) Descriptor() ([]byte, []int) {
	return file_cdc_proto_rawDescGZIP(), []int{22}
}

func (x *GetConsumerInfoResponse) GetAckFloor() uint64 {
	if x != nil {
		return x.AckFloor
	}
	return 0
}

func (x *GetConsumerInfoResponse) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

var File_cdc_proto protoreflect.FileDescriptor

const file_cdc_proto_rawDesc = "" +
	"\n" +
	"\tcdc.proto\x12\x06cdc.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10GetConfigRequest\"\x94\x01\n" +
	"\x11GetConfigResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.cdc.v1.AppConfigR\x06config\x12+\n" +
	"\x11available_sources\x18\x02 \x03(\tR\x10availableSources\x12'\n" +
	"\x0favailable_sinks\x18\x03 \x03(\tR\x0eavailableSinks\"\x94\x01\n" +
	"\tAppConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\blog_mode\x18\x02 \x01(\tR\alogMode\x12.\n" +
	"\asources\x18\x03 \x03(\v2\x14.cdc.v1.SourceConfigR\asources\x12(\n" +
	"\x05sinks\x18\x04 \x03(\v2\x12.cdc.v1.SinkConfigR\x05sinks\"\xa7\x03\n" +
	"\fSourceConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x01R\bpassword\x88\x01\x01\x12\x1a\n" +
	"\bdatabase\x18\x06 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06tables\x18\a \x03(\tR\x06tables\x12 \n" +
	"\tslot_name\x18\b \x01(\tH\x02R\bslotName\x88\x01\x01\x12.\n" +
	"\x10publication_name\x18\t \x01(\tH\x03R\x0fpublicationName\x88\x01\x01\x12$\n" +
	"\vinstance_id\x18\n" +
	" \x01(\tH\x04R\n" +
	"instanceId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\v \x01(\tH\x05R\x04name\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_slot_nameB\x13\n" +
	"\x11_publication_nameB\x0e\n" +
	"\f_instance_idB\a\n" +
	"\x05_name\"\xe5\x05\n" +
	"\n" +
	"SinkConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x03(\tR\x03url\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x01R\bpassword\x88\x01\x01\x12&\n" +
	"\findex_prefix\x18\x05 \x01(\tH\x02R\vindexPrefix\x88\x01\x01\x12\x19\n" +
	"\x05index\x18\x06 \x01(\tH\x03R\x05index\x88\x01\x01\x12I\n" +
	"\rindex_mapping\x18\a \x03(\v2$.cdc.v1.SinkConfig.IndexMappingEntryR\findexMapping\x12\"\n" +
	"\n" +
	"batch_size\x18\b \x01(\x05H\x04R\tbatchSize\x88\x01\x01\x12/\n" +
	"\x11flush_interval_ms\x18\t \x01(\x05H\x05R\x0fflushIntervalMs\x88\x01\x01\x12$\n" +
	"\vmax_retries\x18\n" +
	" \x01(\x05H\x06R\n" +
	"maxRetries\x88\x01\x01\x12'\n" +
	"\rretry_base_ms\x18\v \x01(\x05H\aR\vretryBaseMs\x88\x01\x01\x12\x1c\n" +
	"\aapi_key\x18\f \x01(\tH\bR\x06apiKey\x88\x01\x01\x12$\n" +
	"\vinstance_id\x18\r \x01(\tH\tR\n" +
	"instanceId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x0e \x01(\tH\n" +
	"R\x04name\x88\x01\x01\x1a?\n" +
	"\x11IndexMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\x0f\n" +
	"\r_index_prefixB\b\n" +
	"\x06_indexB\r\n" +
	"\v_batch_sizeB\x14\n" +
	"\x12_flush_interval_msB\x0e\n" +
	"\f_max_retriesB\x10\n" +
	"\x0e_retry_base_msB\n" +
	"\n" +
	"\b_api_keyB\x0e\n" +
	"\f_instance_idB\a\n" +
	"\x05_name\"@\n" +
	"\x10AddSourceRequest\x12,\n" +
	"\x06source\x18\x01 \x01(\v2\x14.cdc.v1.SourceConfigR\x06source\"4\n" +
	"\x11AddSourceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"6\n" +
	"\x13RemoveSourceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"0\n" +
	"\x14RemoveSourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x0eAddSinkRequest\x12&\n" +
	"\x04sink\x18\x01 \x01(\v2\x12.cdc.v1.SinkConfigR\x04sink\"2\n" +
	"\x0fAddSinkResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"4\n" +
	"\x11RemoveSinkRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\".\n" +
	"\x12RemoveSinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"_\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\"\x11\n" +
	"\x0fGetStatsRequest\"\xd6\x02\n" +
	"\x10GetStatsResponse\x12L\n" +
	"\fsource_stats\x18\x01 \x03(\v2).cdc.v1.GetStatsResponse.SourceStatsEntryR\vsourceStats\x12F\n" +
	"\n" +
	"sink_stats\x18\x02 \x03(\v2'.cdc.v1.GetStatsResponse.SinkStatsEntryR\tsinkStats\x1aV\n" +
	"\x10SourceStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.cdc.v1.ComponentStatsR\x05value:\x028\x01\x1aT\n" +
	"\x0eSinkStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.cdc.v1.ComponentStatsR\x05value:\x028\x01\"y\n" +
	"\x0eComponentStats\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x04R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x04R\ffailureCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\"\xa2\x01\n" +
	"\x13ListMessagesRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.cdc.v1.MessageStatusR\x06status\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12 \n" +
	"\tsource_id\x18\x04 \x01(\tH\x00R\bsourceId\x88\x01\x01B\f\n" +
	"\n" +
	"_source_id\"h\n" +
	"\x14ListMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.cdc.v1.MessageItemR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"\xed\x01\n" +
	"\vMessageItem\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12:\n" +
	"\aheaders\x18\x05 \x03(\v2 .cdc.v1.MessageItem.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x16GetConsumerInfoRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\"[\n" +
	"\x17GetConsumerInfoResponse\x12\x1b\n" +
	"\tack_floor\x18\x01 \x01(\x04R\backFloor\x12#\n" +
	"\rpending_count\x18\x02 \x01(\x04R\fpendingCount*c\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x19\n" +
	"\x15MESSAGE_STATUS_UNSENT\x10\x022\xff\x06\n" +
	"\n" +
	"CDCService\x12^\n" +
	"\vHealthCheck\x12\x1a.cdc.v1.HealthCheckRequest\x1a\x1b.cdc.v1.HealthCheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12X\n" +
	"\tGetConfig\x12\x18.cdc.v1.GetConfigRequest\x1a\x19.cdc.v1.GetConfigResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/config\x12\\\n" +
	"\tAddSource\x12\x18.cdc.v1.AddSourceRequest\x1a\x19.cdc.v1.AddSourceResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/sources\x12p\n" +
	"\fRemoveSource\x12\x1b.cdc.v1.RemoveSourceRequest\x1a\x1c.cdc.v1.RemoveSourceResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/sources/{instance_id}\x12T\n" +
	"\aAddSink\x12\x16.cdc.v1.AddSinkRequest\x1a\x17.cdc.v1.AddSinkResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/sinks\x12h\n" +
	"\n" +
	"RemoveSink\x12\x19.cdc.v1.RemoveSinkRequest\x1a\x1a.cdc.v1.RemoveSinkResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/sinks/{instance_id}\x12T\n" +
	"\bGetStats\x12\x17.cdc.v1.GetStatsRequest\x1a\x18.cdc.v1.GetStatsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/stats\x12c\n" +
	"\fListMessages\x12\x1b.cdc.v1.ListMessagesRequest\x1a\x1c.cdc.v1.ListMessagesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/messages\x12l\n" +
	"\x0fGetConsumerInfo\x12\x1e.cdc.v1.GetConsumerInfoRequest\x1a\x1f.cdc.v1.GetConsumerInfoResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/consumerB)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_cdc_proto_rawDescOnce sync.Once
	file_cdc_proto_rawDescData []byte
)

func file_cdc_proto_rawDescGZIP() []byte {
	file_cdc_proto_rawDescOnce.Do(func() {
		file_cdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdc_proto_rawDesc), len(file_cdc_proto_rawDesc)))
	})
	return file_cdc_proto_rawDescData
}

var file_cdc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cdc_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cdc_proto_goTypes = []any{
	(MessageStatus)(0),              // 0: cdc.v1.MessageStatus
	(*GetConfigRequest)(nil),        // 1: cdc.v1.GetConfigRequest
	(*GetConfigResponse)(nil),       // 2: cdc.v1.GetConfigResponse
	(*AppConfig)(nil),               // 3: cdc.v1.AppConfig
	(*SourceConfig)(nil),            // 4: cdc.v1.SourceConfig
	(*SinkConfig)(nil),              // 5: cdc.v1.SinkConfig
	(*AddSourceRequest)(nil),        // 6: cdc.v1.AddSourceRequest
	(*AddSourceResponse)(nil),       // 7: cdc.v1.AddSourceResponse
	(*RemoveSourceRequest)(nil),     // 8: cdc.v1.RemoveSourceRequest
	(*RemoveSourceResponse)(nil),    // 9: cdc.v1.RemoveSourceResponse
	(*AddSinkRequest)(nil),          // 10: cdc.v1.AddSinkRequest
	(*AddSinkResponse)(nil),         // 11: cdc.v1.AddSinkResponse
	(*RemoveSinkRequest)(nil),       // 12: cdc.v1.RemoveSinkRequest
	(*RemoveSinkResponse)(nil),      // 13: cdc.v1.RemoveSinkResponse
	(*HealthCheckRequest)(nil),      // 14: cdc.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 15: cdc.v1.HealthCheckResponse
	(*GetStatsRequest)(nil),         // 16: cdc.v1.GetStatsRequest
	(*GetStatsResponse)(nil),        // 17: cdc.v1.GetStatsResponse
	(*ComponentStats)(nil),          // 18: cdc.v1.ComponentStats
	(*ListMessagesRequest)(nil),     // 19: cdc.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),    // 20: cdc.v1.ListMessagesResponse
	(*MessageItem)(nil),             // 21: cdc.v1.MessageItem
	(*GetConsumerInfoRequest)(nil),  // 22: cdc.v1.GetConsumerInfoRequest
	(*GetConsumerInfoResponse)(nil), // 23: cdc.v1.GetConsumerInfoResponse
	nil,                             // 24: cdc.v1.SinkConfig.IndexMappingEntry
	nil,                             // 25: cdc.v1.GetStatsResponse.SourceStatsEntry
	nil,                             // 26: cdc.v1.GetStatsResponse.SinkStatsEntry
	nil,                             // 27: cdc.v1.MessageItem.HeadersEntry
}
var file_cdc_proto_depIdxs = []int32{
	3,  // 0: cdc.v1.GetConfigResponse.config:type_name -> cdc.v1.AppConfig
	4,  // 1: cdc.v1.AppConfig.sources:type_name -> cdc.v1.SourceConfig
	5,  // 2: cdc.v1.AppConfig.sinks:type_name -> cdc.v1.SinkConfig
	24, // 3: cdc.v1.SinkConfig.index_mapping:type_name -> cdc.v1.SinkConfig.IndexMappingEntry
	4,  // 4: cdc.v1.AddSourceRequest.source:type_name -> cdc.v1.SourceConfig
	5,  // 5: cdc.v1.AddSinkRequest.sink:type_name -> cdc.v1.SinkConfig
	25, // 6: cdc.v1.GetStatsResponse.source_stats:type_name -> cdc.v1.GetStatsResponse.SourceStatsEntry
	26, // 7: cdc.v1.GetStatsResponse.sink_stats:type_name -> cdc.v1.GetStatsResponse.SinkStatsEntry
	0,  // 8: cdc.v1.ListMessagesRequest.status:type_name -> cdc.v1.MessageStatus
	21, // 9: cdc.v1.ListMessagesResponse.messages:type_name -> cdc.v1.MessageItem
	27, // 10: cdc.v1.MessageItem.headers:type_name -> cdc.v1.MessageItem.HeadersEntry
	18, // 11: cdc.v1.GetStatsResponse.SourceStatsEntry.value:type_name -> cdc.v1.ComponentStats
	18, // 12: cdc.v1.GetStatsResponse.SinkStatsEntry.value:type_name -> cdc.v1.ComponentStats
	14, // 13: cdc.v1.CDCService.HealthCheck:input_type -> cdc.v1.HealthCheckRequest
	1,  // 14: cdc.v1.CDCService.GetConfig:input_type -> cdc.v1.GetConfigRequest
	6,  // 15: cdc.v1.CDCService.AddSource:input_type -> cdc.v1.AddSourceRequest
	8,  // 16: cdc.v1.CDCService.RemoveSource:input_type -> cdc.v1.RemoveSourceRequest
	10, // 17: cdc.v1.CDCService.AddSink:input_type -> cdc.v1.AddSinkRequest
	12, // 18: cdc.v1.CDCService.RemoveSink:input_type -> cdc.v1.RemoveSinkRequest
	16, // 19: cdc.v1.CDCService.GetStats:input_type -> cdc.v1.GetStatsRequest
	19, // 20: cdc.v1.CDCService.ListMessages:input_type -> cdc.v1.ListMessagesRequest
	22, // 21: cdc.v1.CDCService.GetConsumerInfo:input_type -> cdc.v1.GetConsumerInfoRequest
	15, // 22: cdc.v1.CDCService.HealthCheck:output_type -> cdc.v1.HealthCheckResponse
	2,  // 23: cdc.v1.CDCService.GetConfig:output_type -> cdc.v1.GetConfigResponse
	7,  // 24: cdc.v1.CDCService.AddSource:output_type -> cdc.v1.AddSourceResponse
	9,  // 25: cdc.v1.CDCService.RemoveSource:output_type -> cdc.v1.RemoveSourceResponse
	11, // 26: cdc.v1.CDCService.AddSink:output_type -> cdc.v1.AddSinkResponse
	13, // 27: cdc.v1.CDCService.RemoveSink:output_type -> cdc.v1.RemoveSinkResponse
	17, // 28: cdc.v1.CDCService.GetStats:output_type -> cdc.v1.GetStatsResponse
	20, // 29: cdc.v1.CDCService.ListMessages:output_type -> cdc.v1.ListMessagesResponse
	23, // 30: cdc.v1.CDCService.GetConsumerInfo:output_type -> cdc.v1.GetConsumerInfoResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cdc_proto_init() }
func file_cdc_proto_init() {
	if File_cdc_proto != nil {
		return
	}
	file_cdc_proto_msgTypes[3].OneofWrappers = []any{}
	file_cdc_proto_msgTypes[4].OneofWrappers = []any{}
	file_cdc_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdc_proto_rawDesc), len(file_cdc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdc_proto_goTypes,
		DependencyIndexes: file_cdc_proto_depIdxs,
		EnumInfos:         file_cdc_proto_enumTypes,
		MessageInfos:      file_cdc_proto_msgTypes,
	}.Build()
	File_cdc_proto = out.File
	file_cdc_proto_goTypes = nil
	file_cdc_proto_depIdxs = nil
}
