// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/v1/cdc.proto

package cdcpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ... messages ...
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{0}
}

type GetConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           *AppConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	AvailableSources []string               `protobuf:"bytes,2,rep,name=available_sources,json=availableSources,proto3" json:"available_sources,omitempty"`
	AvailableSinks   []string               `protobuf:"bytes,3,rep,name=available_sinks,json=availableSinks,proto3" json:"available_sinks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *AppConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetAvailableSources() []string {
	if x != nil {
		return x.AvailableSources
	}
	return nil
}

func (x *GetConfigResponse) GetAvailableSinks() []string {
	if x != nil {
		return x.AvailableSinks
	}
	return nil
}

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogMode       string                 `protobuf:"bytes,2,opt,name=log_mode,json=logMode,proto3" json:"log_mode,omitempty"`
	Source        *SourceConfig          `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Sinks         []*SinkConfig          `protobuf:"bytes,4,rep,name=sinks,proto3" json:"sinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{2}
}

func (x *AppConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppConfig) GetLogMode() string {
	if x != nil {
		return x.LogMode
	}
	return ""
}

func (x *AppConfig) GetSource() *SourceConfig {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AppConfig) GetSinks() []*SinkConfig {
	if x != nil {
		return x.Sinks
	}
	return nil
}

type SourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Tables        []string               `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{3}
}

func (x *SourceConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SourceConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SourceConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SourceConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SourceConfig) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

type SinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           []string               `protobuf:"bytes,2,rep,name=url,proto3" json:"url,omitempty"`
	IndexPrefix   string                 `protobuf:"bytes,3,opt,name=index_prefix,json=indexPrefix,proto3" json:"index_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkConfig) Reset() {
	*x = SinkConfig{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkConfig) ProtoMessage() {}

func (x *SinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkConfig.ProtoReflect.Descriptor instead.
func (*SinkConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{4}
}

func (x *SinkConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SinkConfig) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *SinkConfig) GetIndexPrefix() string {
	if x != nil {
		return x.IndexPrefix
	}
	return ""
}

// Topics
type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{5}
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicSummary        `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{6}
}

func (x *ListTopicsResponse) GetTopics() []*TopicSummary {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PartitionCount int32                  `protobuf:"varint,2,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	MessageCount   uint64                 `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopicSummary) Reset() {
	*x = TopicSummary{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSummary) ProtoMessage() {}

func (x *TopicSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSummary.ProtoReflect.Descriptor instead.
func (*TopicSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{7}
}

func (x *TopicSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicSummary) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *TopicSummary) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TopicDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PartitionCount int32                  `protobuf:"varint,2,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	MessageCount   uint64                 `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Partitions     []*PartitionSummary    `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopicDetail) Reset() {
	*x = TopicDetail{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicDetail) ProtoMessage() {}

func (x *TopicDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicDetail.ProtoReflect.Descriptor instead.
func (*TopicDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{9}
}

func (x *TopicDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicDetail) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *TopicDetail) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *TopicDetail) GetPartitions() []*PartitionSummary {
	if x != nil {
		return x.Partitions
	}
	return nil
}

// Partitions
type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // optional filter by topic
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{10}
}

func (x *ListPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionSummary    `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{11}
}

func (x *ListPartitionsResponse) GetPartitions() []*PartitionSummary {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SegmentCount   int32                  `protobuf:"varint,3,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	EarliestOffset uint64                 `protobuf:"varint,4,opt,name=earliest_offset,json=earliestOffset,proto3" json:"earliest_offset,omitempty"`
	LatestOffset   uint64                 `protobuf:"varint,5,opt,name=latest_offset,json=latestOffset,proto3" json:"latest_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionSummary) Reset() {
	*x = PartitionSummary{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSummary) ProtoMessage() {}

func (x *PartitionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSummary.ProtoReflect.Descriptor instead.
func (*PartitionSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{12}
}

func (x *PartitionSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionSummary) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PartitionSummary) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *PartitionSummary) GetEarliestOffset() uint64 {
	if x != nil {
		return x.EarliestOffset
	}
	return 0
}

func (x *PartitionSummary) GetLatestOffset() uint64 {
	if x != nil {
		return x.LatestOffset
	}
	return 0
}

type GetPartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // topic key (e.g. "db.table")
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionRequest) Reset() {
	*x = GetPartitionRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionRequest) ProtoMessage() {}

func (x *GetPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{13}
}

func (x *GetPartitionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetPartitionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PartitionDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SegmentCount   int32                  `protobuf:"varint,3,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	EarliestOffset uint64                 `protobuf:"varint,4,opt,name=earliest_offset,json=earliestOffset,proto3" json:"earliest_offset,omitempty"`
	LatestOffset   uint64                 `protobuf:"varint,5,opt,name=latest_offset,json=latestOffset,proto3" json:"latest_offset,omitempty"`
	Segments       []*SegmentInfo         `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionDetail) Reset() {
	*x = PartitionDetail{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionDetail) ProtoMessage() {}

func (x *PartitionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionDetail.ProtoReflect.Descriptor instead.
func (*PartitionDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{14}
}

func (x *PartitionDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionDetail) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PartitionDetail) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *PartitionDetail) GetEarliestOffset() uint64 {
	if x != nil {
		return x.EarliestOffset
	}
	return 0
}

func (x *PartitionDetail) GetLatestOffset() uint64 {
	if x != nil {
		return x.LatestOffset
	}
	return 0
}

func (x *PartitionDetail) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseOffset    uint64                 `protobuf:"varint,1,opt,name=base_offset,json=baseOffset,proto3" json:"base_offset,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{15}
}

func (x *SegmentInfo) GetBaseOffset() uint64 {
	if x != nil {
		return x.BaseOffset
	}
	return 0
}

func (x *SegmentInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Messages
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   *int32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3,oneof" json:"partition_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // start reading from this offset
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // max messages to return (default 50)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesRequest) GetPartitionId() int32 {
	if x != nil && x.PartitionId != nil {
		return *x.PartitionId
	}
	return 0
}

func (x *GetMessagesRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageItem         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{17}
}

func (x *GetMessagesResponse) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{18}
}

func (x *MessageItem) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MessageItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Stats / Health
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{19}
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalEnqueued  uint64                 `protobuf:"varint,1,opt,name=total_enqueued,json=totalEnqueued,proto3" json:"total_enqueued,omitempty"`
	TotalDequeued  uint64                 `protobuf:"varint,2,opt,name=total_dequeued,json=totalDequeued,proto3" json:"total_dequeued,omitempty"`
	Pending        uint64                 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	SegmentsCount  int32                  `protobuf:"varint,4,opt,name=segments_count,json=segmentsCount,proto3" json:"segments_count,omitempty"`
	TotalSizeMb    int64                  `protobuf:"varint,5,opt,name=total_size_mb,json=totalSizeMb,proto3" json:"total_size_mb,omitempty"`
	PartitionCount int32                  `protobuf:"varint,6,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{20}
}

func (x *StatsResponse) GetTotalEnqueued() uint64 {
	if x != nil {
		return x.TotalEnqueued
	}
	return 0
}

func (x *StatsResponse) GetTotalDequeued() uint64 {
	if x != nil {
		return x.TotalDequeued
	}
	return 0
}

func (x *StatsResponse) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *StatsResponse) GetSegmentsCount() int32 {
	if x != nil {
		return x.SegmentsCount
	}
	return 0
}

func (x *StatsResponse) GetTotalSizeMb() int64 {
	if x != nil {
		return x.TotalSizeMb
	}
	return 0
}

func (x *StatsResponse) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{21}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"` // seconds since start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_v1_cdc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cdc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cdc_proto_rawDescGZIP(), []int{22}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_api_proto_v1_cdc_proto protoreflect.FileDescriptor

const file_api_proto_v1_cdc_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/v1/cdc.proto\x12\x06cdc.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10GetConfigRequest\"\x94\x01\n" +
	"\x11GetConfigResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.cdc.v1.AppConfigR\x06config\x12+\n" +
	"\x11available_sources\x18\x02 \x03(\tR\x10availableSources\x12'\n" +
	"\x0favailable_sinks\x18\x03 \x03(\tR\x0eavailableSinks\"\x92\x01\n" +
	"\tAppConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\blog_mode\x18\x02 \x01(\tR\alogMode\x12,\n" +
	"\x06source\x18\x03 \x01(\v2\x14.cdc.v1.SourceConfigR\x06source\x12(\n" +
	"\x05sinks\x18\x04 \x03(\v2\x12.cdc.v1.SinkConfigR\x05sinks\"~\n" +
	"\fSourceConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06tables\x18\x05 \x03(\tR\x06tables\"U\n" +
	"\n" +
	"SinkConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x03(\tR\x03url\x12!\n" +
	"\findex_prefix\x18\x03 \x01(\tR\vindexPrefix\"\x13\n" +
	"\x11ListTopicsRequest\"B\n" +
	"\x12ListTopicsResponse\x12,\n" +
	"\x06topics\x18\x01 \x03(\v2\x14.cdc.v1.TopicSummaryR\x06topics\"p\n" +
	"\fTopicSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fpartition_count\x18\x02 \x01(\x05R\x0epartitionCount\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x04R\fmessageCount\"%\n" +
	"\x0fGetTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa9\x01\n" +
	"\vTopicDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fpartition_count\x18\x02 \x01(\x05R\x0epartitionCount\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x04R\fmessageCount\x128\n" +
	"\n" +
	"partitions\x18\x04 \x03(\v2\x18.cdc.v1.PartitionSummaryR\n" +
	"partitions\"-\n" +
	"\x15ListPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"R\n" +
	"\x16ListPartitionsResponse\x128\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x18.cdc.v1.PartitionSummaryR\n" +
	"partitions\"\xb4\x01\n" +
	"\x10PartitionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12#\n" +
	"\rsegment_count\x18\x03 \x01(\x05R\fsegmentCount\x12'\n" +
	"\x0fearliest_offset\x18\x04 \x01(\x04R\x0eearliestOffset\x12#\n" +
	"\rlatest_offset\x18\x05 \x01(\x04R\flatestOffset\";\n" +
	"\x13GetPartitionRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\xe4\x01\n" +
	"\x0fPartitionDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12#\n" +
	"\rsegment_count\x18\x03 \x01(\x05R\fsegmentCount\x12'\n" +
	"\x0fearliest_offset\x18\x04 \x01(\x04R\x0eearliestOffset\x12#\n" +
	"\rlatest_offset\x18\x05 \x01(\x04R\flatestOffset\x12/\n" +
	"\bsegments\x18\x06 \x03(\v2\x13.cdc.v1.SegmentInfoR\bsegments\"M\n" +
	"\vSegmentInfo\x12\x1f\n" +
	"\vbase_offset\x18\x01 \x01(\x04R\n" +
	"baseOffset\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"{\n" +
	"\x12GetMessagesRequest\x12&\n" +
	"\fpartition_id\x18\x01 \x01(\x05H\x00R\vpartitionId\x88\x01\x01\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\x0f\n" +
	"\r_partition_id\"F\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.cdc.v1.MessageItemR\bmessages\"k\n" +
	"\vMessageItem\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"\x11\n" +
	"\x0fGetStatsRequest\"\xeb\x01\n" +
	"\rStatsResponse\x12%\n" +
	"\x0etotal_enqueued\x18\x01 \x01(\x04R\rtotalEnqueued\x12%\n" +
	"\x0etotal_dequeued\x18\x02 \x01(\x04R\rtotalDequeued\x12\x18\n" +
	"\apending\x18\x03 \x01(\x04R\apending\x12%\n" +
	"\x0esegments_count\x18\x04 \x01(\x05R\rsegmentsCount\x12\"\n" +
	"\rtotal_size_mb\x18\x05 \x01(\x03R\vtotalSizeMb\x12'\n" +
	"\x0fpartition_count\x18\x06 \x01(\x05R\x0epartitionCount\"\x14\n" +
	"\x12HealthCheckRequest\"_\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime2\x85\x06\n" +
	"\n" +
	"CDCService\x12[\n" +
	"\n" +
	"ListTopics\x12\x19.cdc.v1.ListTopicsRequest\x1a\x1a.cdc.v1.ListTopicsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/topics\x12W\n" +
	"\bGetTopic\x12\x17.cdc.v1.GetTopicRequest\x1a\x13.cdc.v1.TopicDetail\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/topics/{name}\x12k\n" +
	"\x0eListPartitions\x12\x1d.cdc.v1.ListPartitionsRequest\x1a\x1e.cdc.v1.ListPartitionsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/partitions\x12e\n" +
	"\fGetPartition\x12\x1b.cdc.v1.GetPartitionRequest\x1a\x17.cdc.v1.PartitionDetail\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/partitions/{id}\x12`\n" +
	"\vGetMessages\x12\x1a.cdc.v1.GetMessagesRequest\x1a\x1b.cdc.v1.GetMessagesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/messages\x12Q\n" +
	"\bGetStats\x12\x17.cdc.v1.GetStatsRequest\x1a\x15.cdc.v1.StatsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/stats\x12^\n" +
	"\vHealthCheck\x12\x1a.cdc.v1.HealthCheckRequest\x1a\x1b.cdc.v1.HealthCheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12X\n" +
	"\tGetConfig\x12\x18.cdc.v1.GetConfigRequest\x1a\x19.cdc.v1.GetConfigResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/configB)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_api_proto_v1_cdc_proto_rawDescOnce sync.Once
	file_api_proto_v1_cdc_proto_rawDescData []byte
)

func file_api_proto_v1_cdc_proto_rawDescGZIP() []byte {
	file_api_proto_v1_cdc_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_cdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_cdc_proto_rawDesc), len(file_api_proto_v1_cdc_proto_rawDesc)))
	})
	return file_api_proto_v1_cdc_proto_rawDescData
}

var file_api_proto_v1_cdc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_v1_cdc_proto_goTypes = []any{
	(*GetConfigRequest)(nil),       // 0: cdc.v1.GetConfigRequest
	(*GetConfigResponse)(nil),      // 1: cdc.v1.GetConfigResponse
	(*AppConfig)(nil),              // 2: cdc.v1.AppConfig
	(*SourceConfig)(nil),           // 3: cdc.v1.SourceConfig
	(*SinkConfig)(nil),             // 4: cdc.v1.SinkConfig
	(*ListTopicsRequest)(nil),      // 5: cdc.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),     // 6: cdc.v1.ListTopicsResponse
	(*TopicSummary)(nil),           // 7: cdc.v1.TopicSummary
	(*GetTopicRequest)(nil),        // 8: cdc.v1.GetTopicRequest
	(*TopicDetail)(nil),            // 9: cdc.v1.TopicDetail
	(*ListPartitionsRequest)(nil),  // 10: cdc.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil), // 11: cdc.v1.ListPartitionsResponse
	(*PartitionSummary)(nil),       // 12: cdc.v1.PartitionSummary
	(*GetPartitionRequest)(nil),    // 13: cdc.v1.GetPartitionRequest
	(*PartitionDetail)(nil),        // 14: cdc.v1.PartitionDetail
	(*SegmentInfo)(nil),            // 15: cdc.v1.SegmentInfo
	(*GetMessagesRequest)(nil),     // 16: cdc.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),    // 17: cdc.v1.GetMessagesResponse
	(*MessageItem)(nil),            // 18: cdc.v1.MessageItem
	(*GetStatsRequest)(nil),        // 19: cdc.v1.GetStatsRequest
	(*StatsResponse)(nil),          // 20: cdc.v1.StatsResponse
	(*HealthCheckRequest)(nil),     // 21: cdc.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 22: cdc.v1.HealthCheckResponse
}
var file_api_proto_v1_cdc_proto_depIdxs = []int32{
	2,  // 0: cdc.v1.GetConfigResponse.config:type_name -> cdc.v1.AppConfig
	3,  // 1: cdc.v1.AppConfig.source:type_name -> cdc.v1.SourceConfig
	4,  // 2: cdc.v1.AppConfig.sinks:type_name -> cdc.v1.SinkConfig
	7,  // 3: cdc.v1.ListTopicsResponse.topics:type_name -> cdc.v1.TopicSummary
	12, // 4: cdc.v1.TopicDetail.partitions:type_name -> cdc.v1.PartitionSummary
	12, // 5: cdc.v1.ListPartitionsResponse.partitions:type_name -> cdc.v1.PartitionSummary
	15, // 6: cdc.v1.PartitionDetail.segments:type_name -> cdc.v1.SegmentInfo
	18, // 7: cdc.v1.GetMessagesResponse.messages:type_name -> cdc.v1.MessageItem
	5,  // 8: cdc.v1.CDCService.ListTopics:input_type -> cdc.v1.ListTopicsRequest
	8,  // 9: cdc.v1.CDCService.GetTopic:input_type -> cdc.v1.GetTopicRequest
	10, // 10: cdc.v1.CDCService.ListPartitions:input_type -> cdc.v1.ListPartitionsRequest
	13, // 11: cdc.v1.CDCService.GetPartition:input_type -> cdc.v1.GetPartitionRequest
	16, // 12: cdc.v1.CDCService.GetMessages:input_type -> cdc.v1.GetMessagesRequest
	19, // 13: cdc.v1.CDCService.GetStats:input_type -> cdc.v1.GetStatsRequest
	21, // 14: cdc.v1.CDCService.HealthCheck:input_type -> cdc.v1.HealthCheckRequest
	0,  // 15: cdc.v1.CDCService.GetConfig:input_type -> cdc.v1.GetConfigRequest
	6,  // 16: cdc.v1.CDCService.ListTopics:output_type -> cdc.v1.ListTopicsResponse
	9,  // 17: cdc.v1.CDCService.GetTopic:output_type -> cdc.v1.TopicDetail
	11, // 18: cdc.v1.CDCService.ListPartitions:output_type -> cdc.v1.ListPartitionsResponse
	14, // 19: cdc.v1.CDCService.GetPartition:output_type -> cdc.v1.PartitionDetail
	17, // 20: cdc.v1.CDCService.GetMessages:output_type -> cdc.v1.GetMessagesResponse
	20, // 21: cdc.v1.CDCService.GetStats:output_type -> cdc.v1.StatsResponse
	22, // 22: cdc.v1.CDCService.HealthCheck:output_type -> cdc.v1.HealthCheckResponse
	1,  // 23: cdc.v1.CDCService.GetConfig:output_type -> cdc.v1.GetConfigResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_v1_cdc_proto_init() }
func file_api_proto_v1_cdc_proto_init() {
	if File_api_proto_v1_cdc_proto != nil {
		return
	}
	file_api_proto_v1_cdc_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_cdc_proto_rawDesc), len(file_api_proto_v1_cdc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_cdc_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_cdc_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_cdc_proto_msgTypes,
	}.Build()
	File_api_proto_v1_cdc_proto = out.File
	file_api_proto_v1_cdc_proto_goTypes = nil
	file_api_proto_v1_cdc_proto_depIdxs = nil
}
