// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dashboard.proto

package cdcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryRequest) Reset() {
	*x = GetDashboardSummaryRequest{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryRequest) ProtoMessage() {}

func (x *GetDashboardSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

type GetDashboardSummaryResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Inventory     *DashboardSystemInventory `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Telemetry     *DashboardLiveTelemetry   `protobuf:"bytes,2,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryResponse) Reset() {
	*x = GetDashboardSummaryResponse{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryResponse) ProtoMessage() {}

func (x *GetDashboardSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardSummaryResponse) GetInventory() *DashboardSystemInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *GetDashboardSummaryResponse) GetTelemetry() *DashboardLiveTelemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type DashboardSystemInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcesCount  int32                  `protobuf:"varint,1,opt,name=sources_count,json=sourcesCount,proto3" json:"sources_count,omitempty"`
	SinksCount    int32                  `protobuf:"varint,2,opt,name=sinks_count,json=sinksCount,proto3" json:"sinks_count,omitempty"`
	FlowsCount    int32                  `protobuf:"varint,3,opt,name=flows_count,json=flowsCount,proto3" json:"flows_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSystemInventory) Reset() {
	*x = DashboardSystemInventory{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSystemInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSystemInventory) ProtoMessage() {}

func (x *DashboardSystemInventory) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSystemInventory.ProtoReflect.Descriptor instead.
func (*DashboardSystemInventory) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardSystemInventory) GetSourcesCount() int32 {
	if x != nil {
		return x.SourcesCount
	}
	return 0
}

func (x *DashboardSystemInventory) GetSinksCount() int32 {
	if x != nil {
		return x.SinksCount
	}
	return 0
}

func (x *DashboardSystemInventory) GetFlowsCount() int32 {
	if x != nil {
		return x.FlowsCount
	}
	return 0
}

type DashboardLiveTelemetry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Throughput         float64                `protobuf:"fixed64,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	LatencyP99         float64                `protobuf:"fixed64,2,opt,name=latency_p99,json=latencyP99,proto3" json:"latency_p99,omitempty"`
	ActiveWorkers      uint32                 `protobuf:"varint,3,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	ChannelUtilization float64                `protobuf:"fixed64,4,opt,name=channel_utilization,json=channelUtilization,proto3" json:"channel_utilization,omitempty"`
	NatsHealthy        bool                   `protobuf:"varint,5,opt,name=nats_healthy,json=natsHealthy,proto3" json:"nats_healthy,omitempty"`
	ErrorRate          float64                `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	TotalSyncedEvents  uint64                 `protobuf:"varint,7,opt,name=total_synced_events,json=totalSyncedEvents,proto3" json:"total_synced_events,omitempty"`
	FailureCount       uint64                 `protobuf:"varint,8,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DashboardLiveTelemetry) Reset() {
	*x = DashboardLiveTelemetry{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardLiveTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardLiveTelemetry) ProtoMessage() {}

func (x *DashboardLiveTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardLiveTelemetry.ProtoReflect.Descriptor instead.
func (*DashboardLiveTelemetry) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardLiveTelemetry) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetLatencyP99() float64 {
	if x != nil {
		return x.LatencyP99
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetActiveWorkers() uint32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetChannelUtilization() float64 {
	if x != nil {
		return x.ChannelUtilization
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetNatsHealthy() bool {
	if x != nil {
		return x.NatsHealthy
	}
	return false
}

func (x *DashboardLiveTelemetry) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetTotalSyncedEvents() uint64 {
	if x != nil {
		return x.TotalSyncedEvents
	}
	return 0
}

func (x *DashboardLiveTelemetry) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\x06cdc.v1\"\x1c\n" +
	"\x1aGetDashboardSummaryRequest\"\x9b\x01\n" +
	"\x1bGetDashboardSummaryResponse\x12>\n" +
	"\tinventory\x18\x01 \x01(\v2 .cdc.v1.DashboardSystemInventoryR\tinventory\x12<\n" +
	"\ttelemetry\x18\x02 \x01(\v2\x1e.cdc.v1.DashboardLiveTelemetryR\ttelemetry\"\x81\x01\n" +
	"\x18DashboardSystemInventory\x12#\n" +
	"\rsources_count\x18\x01 \x01(\x05R\fsourcesCount\x12\x1f\n" +
	"\vsinks_count\x18\x02 \x01(\x05R\n" +
	"sinksCount\x12\x1f\n" +
	"\vflows_count\x18\x03 \x01(\x05R\n" +
	"flowsCount\"\xc8\x02\n" +
	"\x16DashboardLiveTelemetry\x12\x1e\n" +
	"\n" +
	"throughput\x18\x01 \x01(\x01R\n" +
	"throughput\x12\x1f\n" +
	"\vlatency_p99\x18\x02 \x01(\x01R\n" +
	"latencyP99\x12%\n" +
	"\x0eactive_workers\x18\x03 \x01(\rR\ractiveWorkers\x12/\n" +
	"\x13channel_utilization\x18\x04 \x01(\x01R\x12channelUtilization\x12!\n" +
	"\fnats_healthy\x18\x05 \x01(\bR\vnatsHealthy\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate\x12.\n" +
	"\x13total_synced_events\x18\a \x01(\x04R\x11totalSyncedEvents\x12#\n" +
	"\rfailure_count\x18\b \x01(\x04R\ffailureCountB)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dashboard_proto_goTypes = []any{
	(*GetDashboardSummaryRequest)(nil),  // 0: cdc.v1.GetDashboardSummaryRequest
	(*GetDashboardSummaryResponse)(nil), // 1: cdc.v1.GetDashboardSummaryResponse
	(*DashboardSystemInventory)(nil),    // 2: cdc.v1.DashboardSystemInventory
	(*DashboardLiveTelemetry)(nil),      // 3: cdc.v1.DashboardLiveTelemetry
}
var file_dashboard_proto_depIdxs = []int32{
	2, // 0: cdc.v1.GetDashboardSummaryResponse.inventory:type_name -> cdc.v1.DashboardSystemInventory
	3, // 1: cdc.v1.GetDashboardSummaryResponse.telemetry:type_name -> cdc.v1.DashboardLiveTelemetry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
