// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: explorer.proto

package cdcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message delivery status.
type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_UNSENT      MessageStatus = 2
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_UNSENT",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENT":        1,
		"MESSAGE_STATUS_UNSENT":      2,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_explorer_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_explorer_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{0}
}

type ExplorerHealthStatus int32

const (
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_UNSPECIFIED ExplorerHealthStatus = 0
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_HEALTHY     ExplorerHealthStatus = 1
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_IDLE        ExplorerHealthStatus = 2
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_LAGGING     ExplorerHealthStatus = 3
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_STALE       ExplorerHealthStatus = 4
	ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_DLQ         ExplorerHealthStatus = 5
)

// Enum value maps for ExplorerHealthStatus.
var (
	ExplorerHealthStatus_name = map[int32]string{
		0: "EXPLORER_HEALTH_STATUS_UNSPECIFIED",
		1: "EXPLORER_HEALTH_STATUS_HEALTHY",
		2: "EXPLORER_HEALTH_STATUS_IDLE",
		3: "EXPLORER_HEALTH_STATUS_LAGGING",
		4: "EXPLORER_HEALTH_STATUS_STALE",
		5: "EXPLORER_HEALTH_STATUS_DLQ",
	}
	ExplorerHealthStatus_value = map[string]int32{
		"EXPLORER_HEALTH_STATUS_UNSPECIFIED": 0,
		"EXPLORER_HEALTH_STATUS_HEALTHY":     1,
		"EXPLORER_HEALTH_STATUS_IDLE":        2,
		"EXPLORER_HEALTH_STATUS_LAGGING":     3,
		"EXPLORER_HEALTH_STATUS_STALE":       4,
		"EXPLORER_HEALTH_STATUS_DLQ":         5,
	}
)

func (x ExplorerHealthStatus) Enum() *ExplorerHealthStatus {
	p := new(ExplorerHealthStatus)
	*p = x
	return p
}

func (x ExplorerHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExplorerHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_explorer_proto_enumTypes[1].Descriptor()
}

func (ExplorerHealthStatus) Type() protoreflect.EnumType {
	return &file_explorer_proto_enumTypes[1]
}

func (x ExplorerHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExplorerHealthStatus.Descriptor instead.
func (ExplorerHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{1}
}

type ExplorerSort int32

const (
	ExplorerSort_EXPLORER_SORT_UNSPECIFIED  ExplorerSort = 0
	ExplorerSort_EXPLORER_SORT_NEWEST_FIRST ExplorerSort = 1
	ExplorerSort_EXPLORER_SORT_OLDEST_FIRST ExplorerSort = 2
)

// Enum value maps for ExplorerSort.
var (
	ExplorerSort_name = map[int32]string{
		0: "EXPLORER_SORT_UNSPECIFIED",
		1: "EXPLORER_SORT_NEWEST_FIRST",
		2: "EXPLORER_SORT_OLDEST_FIRST",
	}
	ExplorerSort_value = map[string]int32{
		"EXPLORER_SORT_UNSPECIFIED":  0,
		"EXPLORER_SORT_NEWEST_FIRST": 1,
		"EXPLORER_SORT_OLDEST_FIRST": 2,
	}
)

func (x ExplorerSort) Enum() *ExplorerSort {
	p := new(ExplorerSort)
	*p = x
	return p
}

func (x ExplorerSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExplorerSort) Descriptor() protoreflect.EnumDescriptor {
	return file_explorer_proto_enumTypes[2].Descriptor()
}

func (ExplorerSort) Type() protoreflect.EnumType {
	return &file_explorer_proto_enumTypes[2]
}

func (x ExplorerSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExplorerSort.Descriptor instead.
func (ExplorerSort) EnumDescriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{2}
}

type ExplorerScanMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partial       bool                   `protobuf:"varint,1,opt,name=partial,proto3" json:"partial,omitempty"`
	ScanLimitHit  bool                   `protobuf:"varint,2,opt,name=scan_limit_hit,json=scanLimitHit,proto3" json:"scan_limit_hit,omitempty"`
	ScannedCount  uint64                 `protobuf:"varint,3,opt,name=scanned_count,json=scannedCount,proto3" json:"scanned_count,omitempty"`
	MatchedCount  uint64                 `protobuf:"varint,4,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	MaxScan       uint64                 `protobuf:"varint,5,opt,name=max_scan,json=maxScan,proto3" json:"max_scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplorerScanMetadata) Reset() {
	*x = ExplorerScanMetadata{}
	mi := &file_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplorerScanMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplorerScanMetadata) ProtoMessage() {}

func (x *ExplorerScanMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplorerScanMetadata.ProtoReflect.Descriptor instead.
func (*ExplorerScanMetadata) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *ExplorerScanMetadata) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *ExplorerScanMetadata) GetScanLimitHit() bool {
	if x != nil {
		return x.ScanLimitHit
	}
	return false
}

func (x *ExplorerScanMetadata) GetScannedCount() uint64 {
	if x != nil {
		return x.ScannedCount
	}
	return 0
}

func (x *ExplorerScanMetadata) GetMatchedCount() uint64 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *ExplorerScanMetadata) GetMaxScan() uint64 {
	if x != nil {
		return x.MaxScan
	}
	return 0
}

// Request to list messages with optional filters.
type ListMessagesRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Status          MessageStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=cdc.v1.MessageStatus" json:"status,omitempty"`
	SourceId        *string                  `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	Topic           *string                  `protobuf:"bytes,3,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	Partition       *string                  `protobuf:"bytes,4,opt,name=partition,proto3,oneof" json:"partition,omitempty"`
	Pagination      *OffsetPaginationRequest `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Schema          *string                  `protobuf:"bytes,6,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	Table           *string                  `protobuf:"bytes,7,opt,name=table,proto3,oneof" json:"table,omitempty"`
	Op              *string                  `protobuf:"bytes,8,opt,name=op,proto3,oneof" json:"op,omitempty"`
	SequenceMin     *uint64                  `protobuf:"varint,9,opt,name=sequence_min,json=sequenceMin,proto3,oneof" json:"sequence_min,omitempty"`
	SequenceMax     *uint64                  `protobuf:"varint,10,opt,name=sequence_max,json=sequenceMax,proto3,oneof" json:"sequence_max,omitempty"`
	TimestampFrom   *int64                   `protobuf:"varint,11,opt,name=timestamp_from,json=timestampFrom,proto3,oneof" json:"timestamp_from,omitempty"`
	TimestampTo     *int64                   `protobuf:"varint,12,opt,name=timestamp_to,json=timestampTo,proto3,oneof" json:"timestamp_to,omitempty"`
	HeaderKey       *string                  `protobuf:"bytes,13,opt,name=header_key,json=headerKey,proto3,oneof" json:"header_key,omitempty"`
	HeaderValue     *string                  `protobuf:"bytes,14,opt,name=header_value,json=headerValue,proto3,oneof" json:"header_value,omitempty"`
	JsonPath        *string                  `protobuf:"bytes,15,opt,name=json_path,json=jsonPath,proto3,oneof" json:"json_path,omitempty"`
	JsonEquals      *string                  `protobuf:"bytes,16,opt,name=json_equals,json=jsonEquals,proto3,oneof" json:"json_equals,omitempty"`
	TextContains    *string                  `protobuf:"bytes,17,opt,name=text_contains,json=textContains,proto3,oneof" json:"text_contains,omitempty"`
	ReprocessedOnly bool                     `protobuf:"varint,18,opt,name=reprocessed_only,json=reprocessedOnly,proto3" json:"reprocessed_only,omitempty"`
	DlqRelatedOnly  bool                     `protobuf:"varint,19,opt,name=dlq_related_only,json=dlqRelatedOnly,proto3" json:"dlq_related_only,omitempty"`
	Sort            ExplorerSort             `protobuf:"varint,20,opt,name=sort,proto3,enum=cdc.v1.ExplorerSort" json:"sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *ListMessagesRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ListMessagesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListMessagesRequest) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *ListMessagesRequest) GetPartition() string {
	if x != nil && x.Partition != nil {
		return *x.Partition
	}
	return ""
}

func (x *ListMessagesRequest) GetPagination() *OffsetPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMessagesRequest) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

func (x *ListMessagesRequest) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *ListMessagesRequest) GetOp() string {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return ""
}

func (x *ListMessagesRequest) GetSequenceMin() uint64 {
	if x != nil && x.SequenceMin != nil {
		return *x.SequenceMin
	}
	return 0
}

func (x *ListMessagesRequest) GetSequenceMax() uint64 {
	if x != nil && x.SequenceMax != nil {
		return *x.SequenceMax
	}
	return 0
}

func (x *ListMessagesRequest) GetTimestampFrom() int64 {
	if x != nil && x.TimestampFrom != nil {
		return *x.TimestampFrom
	}
	return 0
}

func (x *ListMessagesRequest) GetTimestampTo() int64 {
	if x != nil && x.TimestampTo != nil {
		return *x.TimestampTo
	}
	return 0
}

func (x *ListMessagesRequest) GetHeaderKey() string {
	if x != nil && x.HeaderKey != nil {
		return *x.HeaderKey
	}
	return ""
}

func (x *ListMessagesRequest) GetHeaderValue() string {
	if x != nil && x.HeaderValue != nil {
		return *x.HeaderValue
	}
	return ""
}

func (x *ListMessagesRequest) GetJsonPath() string {
	if x != nil && x.JsonPath != nil {
		return *x.JsonPath
	}
	return ""
}

func (x *ListMessagesRequest) GetJsonEquals() string {
	if x != nil && x.JsonEquals != nil {
		return *x.JsonEquals
	}
	return ""
}

func (x *ListMessagesRequest) GetTextContains() string {
	if x != nil && x.TextContains != nil {
		return *x.TextContains
	}
	return ""
}

func (x *ListMessagesRequest) GetReprocessedOnly() bool {
	if x != nil {
		return x.ReprocessedOnly
	}
	return false
}

func (x *ListMessagesRequest) GetDlqRelatedOnly() bool {
	if x != nil {
		return x.DlqRelatedOnly
	}
	return false
}

func (x *ListMessagesRequest) GetSort() ExplorerSort {
	if x != nil {
		return x.Sort
	}
	return ExplorerSort_EXPLORER_SORT_UNSPECIFIED
}

// Response containing a page of messages.
type ListMessagesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*MessageItem            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    uint64                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Pagination    *OffsetPaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Scan          *ExplorerScanMetadata     `protobuf:"bytes,4,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessagesResponse) GetData() []*MessageItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListMessagesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMessagesResponse) GetPagination() *OffsetPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMessagesResponse) GetScan() *ExplorerScanMetadata {
	if x != nil {
		return x.Scan
	}
	return nil
}

// A single message item.
type MessageItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sequence        uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp       string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Subject         string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Op              string                 `protobuf:"bytes,6,opt,name=op,proto3" json:"op,omitempty"`
	SourceId        string                 `protobuf:"bytes,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Schema          string                 `protobuf:"bytes,8,opt,name=schema,proto3" json:"schema,omitempty"`
	Table           string                 `protobuf:"bytes,9,opt,name=table,proto3" json:"table,omitempty"`
	Partition       string                 `protobuf:"bytes,10,opt,name=partition,proto3" json:"partition,omitempty"`
	Key             string                 `protobuf:"bytes,11,opt,name=key,proto3" json:"key,omitempty"`
	PayloadSize     uint64                 `protobuf:"varint,12,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	HeaderCount     uint32                 `protobuf:"varint,13,opt,name=header_count,json=headerCount,proto3" json:"header_count,omitempty"`
	NatsMsgId       string                 `protobuf:"bytes,14,opt,name=nats_msg_id,json=natsMsgId,proto3" json:"nats_msg_id,omitempty"`
	ReprocessedFrom string                 `protobuf:"bytes,15,opt,name=reprocessed_from,json=reprocessedFrom,proto3" json:"reprocessed_from,omitempty"`
	Markers         []string               `protobuf:"bytes,16,rep,name=markers,proto3" json:"markers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_explorer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *MessageItem) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MessageItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MessageItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MessageItem) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *MessageItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *MessageItem) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *MessageItem) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *MessageItem) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *MessageItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MessageItem) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *MessageItem) GetHeaderCount() uint32 {
	if x != nil {
		return x.HeaderCount
	}
	return 0
}

func (x *MessageItem) GetNatsMsgId() string {
	if x != nil {
		return x.NatsMsgId
	}
	return ""
}

func (x *MessageItem) GetReprocessedFrom() string {
	if x != nil {
		return x.ReprocessedFrom
	}
	return ""
}

func (x *MessageItem) GetMarkers() []string {
	if x != nil {
		return x.Markers
	}
	return nil
}

type GetExplorerOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplorerOverviewRequest) Reset() {
	*x = GetExplorerOverviewRequest{}
	mi := &file_explorer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplorerOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplorerOverviewRequest) ProtoMessage() {}

func (x *GetExplorerOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplorerOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetExplorerOverviewRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{4}
}

type GetExplorerOverviewResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TopicCount             uint64                 `protobuf:"varint,1,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	PartitionCount         uint64                 `protobuf:"varint,2,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	ConsumerCount          uint64                 `protobuf:"varint,3,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	PendingCount           uint64                 `protobuf:"varint,4,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	AckPendingCount        uint64                 `protobuf:"varint,5,opt,name=ack_pending_count,json=ackPendingCount,proto3" json:"ack_pending_count,omitempty"`
	DlqDepth               uint64                 `protobuf:"varint,6,opt,name=dlq_depth,json=dlqDepth,proto3" json:"dlq_depth,omitempty"`
	TopicsNeedingAttention []*TopicSummary        `protobuf:"bytes,7,rep,name=topics_needing_attention,json=topicsNeedingAttention,proto3" json:"topics_needing_attention,omitempty"`
	RecentDlq              []*DLQMessageSummary   `protobuf:"bytes,8,rep,name=recent_dlq,json=recentDlq,proto3" json:"recent_dlq,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetExplorerOverviewResponse) Reset() {
	*x = GetExplorerOverviewResponse{}
	mi := &file_explorer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplorerOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplorerOverviewResponse) ProtoMessage() {}

func (x *GetExplorerOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplorerOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetExplorerOverviewResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *GetExplorerOverviewResponse) GetTopicCount() uint64 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetPartitionCount() uint64 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetConsumerCount() uint64 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetAckPendingCount() uint64 {
	if x != nil {
		return x.AckPendingCount
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetDlqDepth() uint64 {
	if x != nil {
		return x.DlqDepth
	}
	return 0
}

func (x *GetExplorerOverviewResponse) GetTopicsNeedingAttention() []*TopicSummary {
	if x != nil {
		return x.TopicsNeedingAttention
	}
	return nil
}

func (x *GetExplorerOverviewResponse) GetRecentDlq() []*DLQMessageSummary {
	if x != nil {
		return x.RecentDlq
	}
	return nil
}

type GetTopicDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicDetailRequest) Reset() {
	*x = GetTopicDetailRequest{}
	mi := &file_explorer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicDetailRequest) ProtoMessage() {}

func (x *GetTopicDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTopicDetailRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopicDetailRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetTopicDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *TopicSummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Partitions    []*PartitionSummary    `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Scan          *ExplorerScanMetadata  `protobuf:"bytes,3,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicDetailResponse) Reset() {
	*x = GetTopicDetailResponse{}
	mi := &file_explorer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicDetailResponse) ProtoMessage() {}

func (x *GetTopicDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicDetailResponse.ProtoReflect.Descriptor instead.
func (*GetTopicDetailResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopicDetailResponse) GetSummary() *TopicSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetTopicDetailResponse) GetPartitions() []*PartitionSummary {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *GetTopicDetailResponse) GetScan() *ExplorerScanMetadata {
	if x != nil {
		return x.Scan
	}
	return nil
}

type GetPartitionDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionDetailRequest) Reset() {
	*x = GetPartitionDetailRequest{}
	mi := &file_explorer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionDetailRequest) ProtoMessage() {}

func (x *GetPartitionDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionDetailRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionDetailRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{8}
}

func (x *GetPartitionDetailRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetPartitionDetailRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type GetPartitionDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        *PartitionSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	RecentMessages []*MessageItem         `protobuf:"bytes,2,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	Checkpoints    []*CheckpointContext   `protobuf:"bytes,3,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	Scan           *ExplorerScanMetadata  `protobuf:"bytes,4,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPartitionDetailResponse) Reset() {
	*x = GetPartitionDetailResponse{}
	mi := &file_explorer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionDetailResponse) ProtoMessage() {}

func (x *GetPartitionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionDetailResponse.ProtoReflect.Descriptor instead.
func (*GetPartitionDetailResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{9}
}

func (x *GetPartitionDetailResponse) GetSummary() *PartitionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetPartitionDetailResponse) GetRecentMessages() []*MessageItem {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

func (x *GetPartitionDetailResponse) GetCheckpoints() []*CheckpointContext {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *GetPartitionDetailResponse) GetScan() *ExplorerScanMetadata {
	if x != nil {
		return x.Scan
	}
	return nil
}

type ListPartitionMessagesRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Status          MessageStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=cdc.v1.MessageStatus" json:"status,omitempty"`
	SourceId        *string                  `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	Topic           string                   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition       string                   `protobuf:"bytes,4,opt,name=partition,proto3" json:"partition,omitempty"`
	Pagination      *OffsetPaginationRequest `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Schema          *string                  `protobuf:"bytes,6,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	Table           *string                  `protobuf:"bytes,7,opt,name=table,proto3,oneof" json:"table,omitempty"`
	Op              *string                  `protobuf:"bytes,8,opt,name=op,proto3,oneof" json:"op,omitempty"`
	SequenceMin     *uint64                  `protobuf:"varint,9,opt,name=sequence_min,json=sequenceMin,proto3,oneof" json:"sequence_min,omitempty"`
	SequenceMax     *uint64                  `protobuf:"varint,10,opt,name=sequence_max,json=sequenceMax,proto3,oneof" json:"sequence_max,omitempty"`
	TimestampFrom   *int64                   `protobuf:"varint,11,opt,name=timestamp_from,json=timestampFrom,proto3,oneof" json:"timestamp_from,omitempty"`
	TimestampTo     *int64                   `protobuf:"varint,12,opt,name=timestamp_to,json=timestampTo,proto3,oneof" json:"timestamp_to,omitempty"`
	HeaderKey       *string                  `protobuf:"bytes,13,opt,name=header_key,json=headerKey,proto3,oneof" json:"header_key,omitempty"`
	HeaderValue     *string                  `protobuf:"bytes,14,opt,name=header_value,json=headerValue,proto3,oneof" json:"header_value,omitempty"`
	JsonPath        *string                  `protobuf:"bytes,15,opt,name=json_path,json=jsonPath,proto3,oneof" json:"json_path,omitempty"`
	JsonEquals      *string                  `protobuf:"bytes,16,opt,name=json_equals,json=jsonEquals,proto3,oneof" json:"json_equals,omitempty"`
	TextContains    *string                  `protobuf:"bytes,17,opt,name=text_contains,json=textContains,proto3,oneof" json:"text_contains,omitempty"`
	ReprocessedOnly bool                     `protobuf:"varint,18,opt,name=reprocessed_only,json=reprocessedOnly,proto3" json:"reprocessed_only,omitempty"`
	DlqRelatedOnly  bool                     `protobuf:"varint,19,opt,name=dlq_related_only,json=dlqRelatedOnly,proto3" json:"dlq_related_only,omitempty"`
	Sort            ExplorerSort             `protobuf:"varint,20,opt,name=sort,proto3,enum=cdc.v1.ExplorerSort" json:"sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPartitionMessagesRequest) Reset() {
	*x = ListPartitionMessagesRequest{}
	mi := &file_explorer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionMessagesRequest) ProtoMessage() {}

func (x *ListPartitionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{10}
}

func (x *ListPartitionMessagesRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ListPartitionMessagesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetPagination() *OffsetPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPartitionMessagesRequest) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetOp() string {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetSequenceMin() uint64 {
	if x != nil && x.SequenceMin != nil {
		return *x.SequenceMin
	}
	return 0
}

func (x *ListPartitionMessagesRequest) GetSequenceMax() uint64 {
	if x != nil && x.SequenceMax != nil {
		return *x.SequenceMax
	}
	return 0
}

func (x *ListPartitionMessagesRequest) GetTimestampFrom() int64 {
	if x != nil && x.TimestampFrom != nil {
		return *x.TimestampFrom
	}
	return 0
}

func (x *ListPartitionMessagesRequest) GetTimestampTo() int64 {
	if x != nil && x.TimestampTo != nil {
		return *x.TimestampTo
	}
	return 0
}

func (x *ListPartitionMessagesRequest) GetHeaderKey() string {
	if x != nil && x.HeaderKey != nil {
		return *x.HeaderKey
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetHeaderValue() string {
	if x != nil && x.HeaderValue != nil {
		return *x.HeaderValue
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetJsonPath() string {
	if x != nil && x.JsonPath != nil {
		return *x.JsonPath
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetJsonEquals() string {
	if x != nil && x.JsonEquals != nil {
		return *x.JsonEquals
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetTextContains() string {
	if x != nil && x.TextContains != nil {
		return *x.TextContains
	}
	return ""
}

func (x *ListPartitionMessagesRequest) GetReprocessedOnly() bool {
	if x != nil {
		return x.ReprocessedOnly
	}
	return false
}

func (x *ListPartitionMessagesRequest) GetDlqRelatedOnly() bool {
	if x != nil {
		return x.DlqRelatedOnly
	}
	return false
}

func (x *ListPartitionMessagesRequest) GetSort() ExplorerSort {
	if x != nil {
		return x.Sort
	}
	return ExplorerSort_EXPLORER_SORT_UNSPECIFIED
}

type ListPartitionMessagesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*MessageItem            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    uint64                    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Pagination    *OffsetPaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Scan          *ExplorerScanMetadata     `protobuf:"bytes,4,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionMessagesResponse) Reset() {
	*x = ListPartitionMessagesResponse{}
	mi := &file_explorer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionMessagesResponse) ProtoMessage() {}

func (x *ListPartitionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{11}
}

func (x *ListPartitionMessagesResponse) GetData() []*MessageItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPartitionMessagesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPartitionMessagesResponse) GetPagination() *OffsetPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPartitionMessagesResponse) GetScan() *ExplorerScanMetadata {
	if x != nil {
		return x.Scan
	}
	return nil
}

type GetMessageDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageDetailRequest) Reset() {
	*x = GetMessageDetailRequest{}
	mi := &file_explorer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageDetailRequest) ProtoMessage() {}

func (x *GetMessageDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageDetailRequest.ProtoReflect.Descriptor instead.
func (*GetMessageDetailRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessageDetailRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetMessageDetailRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *GetMessageDetailRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetMessageDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MessageItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Before        []byte                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         []byte                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	ChangedFields []string               `protobuf:"bytes,4,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	Checkpoint    *CheckpointContext     `protobuf:"bytes,5,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageDetailResponse) Reset() {
	*x = GetMessageDetailResponse{}
	mi := &file_explorer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageDetailResponse) ProtoMessage() {}

func (x *GetMessageDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageDetailResponse.ProtoReflect.Descriptor instead.
func (*GetMessageDetailResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessageDetailResponse) GetItem() *MessageItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetMessageDetailResponse) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *GetMessageDetailResponse) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *GetMessageDetailResponse) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *GetMessageDetailResponse) GetCheckpoint() *CheckpointContext {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type CheckpointContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName       string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	DeliveredStreamSeq uint64                 `protobuf:"varint,2,opt,name=delivered_stream_seq,json=deliveredStreamSeq,proto3" json:"delivered_stream_seq,omitempty"`
	AckFloorStreamSeq  uint64                 `protobuf:"varint,3,opt,name=ack_floor_stream_seq,json=ackFloorStreamSeq,proto3" json:"ack_floor_stream_seq,omitempty"`
	NumPending         uint64                 `protobuf:"varint,4,opt,name=num_pending,json=numPending,proto3" json:"num_pending,omitempty"`
	NumAckPending      uint64                 `protobuf:"varint,5,opt,name=num_ack_pending,json=numAckPending,proto3" json:"num_ack_pending,omitempty"`
	LagMessages        uint64                 `protobuf:"varint,6,opt,name=lag_messages,json=lagMessages,proto3" json:"lag_messages,omitempty"`
	LastDeliveredAt    string                 `protobuf:"bytes,7,opt,name=last_delivered_at,json=lastDeliveredAt,proto3" json:"last_delivered_at,omitempty"`
	LastAckAt          string                 `protobuf:"bytes,8,opt,name=last_ack_at,json=lastAckAt,proto3" json:"last_ack_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckpointContext) Reset() {
	*x = CheckpointContext{}
	mi := &file_explorer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointContext) ProtoMessage() {}

func (x *CheckpointContext) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointContext.ProtoReflect.Descriptor instead.
func (*CheckpointContext) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{14}
}

func (x *CheckpointContext) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *CheckpointContext) GetDeliveredStreamSeq() uint64 {
	if x != nil {
		return x.DeliveredStreamSeq
	}
	return 0
}

func (x *CheckpointContext) GetAckFloorStreamSeq() uint64 {
	if x != nil {
		return x.AckFloorStreamSeq
	}
	return 0
}

func (x *CheckpointContext) GetNumPending() uint64 {
	if x != nil {
		return x.NumPending
	}
	return 0
}

func (x *CheckpointContext) GetNumAckPending() uint64 {
	if x != nil {
		return x.NumAckPending
	}
	return 0
}

func (x *CheckpointContext) GetLagMessages() uint64 {
	if x != nil {
		return x.LagMessages
	}
	return 0
}

func (x *CheckpointContext) GetLastDeliveredAt() string {
	if x != nil {
		return x.LastDeliveredAt
	}
	return ""
}

func (x *CheckpointContext) GetLastAckAt() string {
	if x != nil {
		return x.LastAckAt
	}
	return ""
}

type DLQMessageSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DlqId           string                 `protobuf:"bytes,1,opt,name=dlq_id,json=dlqId,proto3" json:"dlq_id,omitempty"`
	OriginalSubject string                 `protobuf:"bytes,2,opt,name=original_subject,json=originalSubject,proto3" json:"original_subject,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorClass      string                 `protobuf:"bytes,4,opt,name=error_class,json=errorClass,proto3" json:"error_class,omitempty"`
	Timestamp       string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DLQMessageSummary) Reset() {
	*x = DLQMessageSummary{}
	mi := &file_explorer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQMessageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQMessageSummary) ProtoMessage() {}

func (x *DLQMessageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQMessageSummary.ProtoReflect.Descriptor instead.
func (*DLQMessageSummary) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{15}
}

func (x *DLQMessageSummary) GetDlqId() string {
	if x != nil {
		return x.DlqId
	}
	return ""
}

func (x *DLQMessageSummary) GetOriginalSubject() string {
	if x != nil {
		return x.OriginalSubject
	}
	return ""
}

func (x *DLQMessageSummary) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DLQMessageSummary) GetErrorClass() string {
	if x != nil {
		return x.ErrorClass
	}
	return ""
}

func (x *DLQMessageSummary) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Request to get consumer information.
type GetConsumerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerInfoRequest) Reset() {
	*x = GetConsumerInfoRequest{}
	mi := &file_explorer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerInfoRequest) ProtoMessage() {}

func (x *GetConsumerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConsumerInfoRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{16}
}

func (x *GetConsumerInfoRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

// Response with consumer state.
type GetConsumerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckFloor      uint64                 `protobuf:"varint,1,opt,name=ack_floor,json=ackFloor,proto3" json:"ack_floor,omitempty"`
	PendingCount  uint64                 `protobuf:"varint,2,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerInfoResponse) Reset() {
	*x = GetConsumerInfoResponse{}
	mi := &file_explorer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerInfoResponse) ProtoMessage() {}

func (x *GetConsumerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConsumerInfoResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{17}
}

func (x *GetConsumerInfoResponse) GetAckFloor() uint64 {
	if x != nil {
		return x.AckFloor
	}
	return 0
}

func (x *GetConsumerInfoResponse) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

type ConsumerSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilterSubjects     []string               `protobuf:"bytes,2,rep,name=filter_subjects,json=filterSubjects,proto3" json:"filter_subjects,omitempty"`
	NumPending         uint64                 `protobuf:"varint,3,opt,name=num_pending,json=numPending,proto3" json:"num_pending,omitempty"`
	NumAckPending      uint64                 `protobuf:"varint,4,opt,name=num_ack_pending,json=numAckPending,proto3" json:"num_ack_pending,omitempty"`
	DeliveredStreamSeq uint64                 `protobuf:"varint,5,opt,name=delivered_stream_seq,json=deliveredStreamSeq,proto3" json:"delivered_stream_seq,omitempty"`
	AckFloorStreamSeq  uint64                 `protobuf:"varint,6,opt,name=ack_floor_stream_seq,json=ackFloorStreamSeq,proto3" json:"ack_floor_stream_seq,omitempty"`
	LagMessages        uint64                 `protobuf:"varint,7,opt,name=lag_messages,json=lagMessages,proto3" json:"lag_messages,omitempty"`
	ReplayRisk         string                 `protobuf:"bytes,8,opt,name=replay_risk,json=replayRisk,proto3" json:"replay_risk,omitempty"`
	LastDeliveredAt    string                 `protobuf:"bytes,9,opt,name=last_delivered_at,json=lastDeliveredAt,proto3" json:"last_delivered_at,omitempty"`
	LastAckAt          string                 `protobuf:"bytes,10,opt,name=last_ack_at,json=lastAckAt,proto3" json:"last_ack_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsumerSummary) Reset() {
	*x = ConsumerSummary{}
	mi := &file_explorer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerSummary) ProtoMessage() {}

func (x *ConsumerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerSummary.ProtoReflect.Descriptor instead.
func (*ConsumerSummary) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{18}
}

func (x *ConsumerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsumerSummary) GetFilterSubjects() []string {
	if x != nil {
		return x.FilterSubjects
	}
	return nil
}

func (x *ConsumerSummary) GetNumPending() uint64 {
	if x != nil {
		return x.NumPending
	}
	return 0
}

func (x *ConsumerSummary) GetNumAckPending() uint64 {
	if x != nil {
		return x.NumAckPending
	}
	return 0
}

func (x *ConsumerSummary) GetDeliveredStreamSeq() uint64 {
	if x != nil {
		return x.DeliveredStreamSeq
	}
	return 0
}

func (x *ConsumerSummary) GetAckFloorStreamSeq() uint64 {
	if x != nil {
		return x.AckFloorStreamSeq
	}
	return 0
}

func (x *ConsumerSummary) GetLagMessages() uint64 {
	if x != nil {
		return x.LagMessages
	}
	return 0
}

func (x *ConsumerSummary) GetReplayRisk() string {
	if x != nil {
		return x.ReplayRisk
	}
	return ""
}

func (x *ConsumerSummary) GetLastDeliveredAt() string {
	if x != nil {
		return x.LastDeliveredAt
	}
	return ""
}

func (x *ConsumerSummary) GetLastAckAt() string {
	if x != nil {
		return x.LastAckAt
	}
	return ""
}

type GetConsumerDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerDetailRequest) Reset() {
	*x = GetConsumerDetailRequest{}
	mi := &file_explorer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerDetailRequest) ProtoMessage() {}

func (x *GetConsumerDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerDetailRequest.ProtoReflect.Descriptor instead.
func (*GetConsumerDetailRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{19}
}

func (x *GetConsumerDetailRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type GetConsumerDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        *ConsumerSummary       `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Topics         []*TopicSummary        `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Partitions     []*PartitionSummary    `protobuf:"bytes,3,rep,name=partitions,proto3" json:"partitions,omitempty"`
	RecentMessages []*MessageItem         `protobuf:"bytes,4,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	Scan           *ExplorerScanMetadata  `protobuf:"bytes,5,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConsumerDetailResponse) Reset() {
	*x = GetConsumerDetailResponse{}
	mi := &file_explorer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerDetailResponse) ProtoMessage() {}

func (x *GetConsumerDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerDetailResponse.ProtoReflect.Descriptor instead.
func (*GetConsumerDetailResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{20}
}

func (x *GetConsumerDetailResponse) GetSummary() *ConsumerSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetConsumerDetailResponse) GetTopics() []*TopicSummary {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *GetConsumerDetailResponse) GetPartitions() []*PartitionSummary {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *GetConsumerDetailResponse) GetRecentMessages() []*MessageItem {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

func (x *GetConsumerDetailResponse) GetScan() *ExplorerScanMetadata {
	if x != nil {
		return x.Scan
	}
	return nil
}

type ListConsumersRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Pagination    *OffsetPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersRequest) Reset() {
	*x = ListConsumersRequest{}
	mi := &file_explorer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersRequest) ProtoMessage() {}

func (x *ListConsumersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersRequest.ProtoReflect.Descriptor instead.
func (*ListConsumersRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{21}
}

func (x *ListConsumersRequest) GetPagination() *OffsetPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListConsumersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*ConsumerSummary        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *OffsetPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersResponse) Reset() {
	*x = ListConsumersResponse{}
	mi := &file_explorer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersResponse) ProtoMessage() {}

func (x *ListConsumersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersResponse.ProtoReflect.Descriptor instead.
func (*ListConsumersResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{22}
}

func (x *ListConsumersResponse) GetData() []*ConsumerSummary {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListConsumersResponse) GetPagination() *OffsetPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request to list topics.
type ListTopicsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Pagination    *OffsetPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_explorer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{23}
}

func (x *ListTopicsRequest) GetPagination() *OffsetPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Response containing a page of topics.
type ListTopicsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*TopicSummary           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *OffsetPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_explorer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{24}
}

func (x *ListTopicsResponse) GetData() []*TopicSummary {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTopicsResponse) GetPagination() *OffsetPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Summary information for a topic.
type TopicSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MessageCount    uint64                 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PartitionCount  int32                  `protobuf:"varint,3,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	ConsumerCount   uint64                 `protobuf:"varint,4,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	DlqCount        uint64                 `protobuf:"varint,5,opt,name=dlq_count,json=dlqCount,proto3" json:"dlq_count,omitempty"`
	PendingCount    uint64                 `protobuf:"varint,6,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	AckPendingCount uint64                 `protobuf:"varint,7,opt,name=ack_pending_count,json=ackPendingCount,proto3" json:"ack_pending_count,omitempty"`
	FirstSequence   uint64                 `protobuf:"varint,8,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	LatestSequence  uint64                 `protobuf:"varint,9,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	LatestEventAt   string                 `protobuf:"bytes,10,opt,name=latest_event_at,json=latestEventAt,proto3" json:"latest_event_at,omitempty"`
	Health          ExplorerHealthStatus   `protobuf:"varint,11,opt,name=health,proto3,enum=cdc.v1.ExplorerHealthStatus" json:"health,omitempty"`
	Partial         bool                   `protobuf:"varint,12,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TopicSummary) Reset() {
	*x = TopicSummary{}
	mi := &file_explorer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSummary) ProtoMessage() {}

func (x *TopicSummary) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSummary.ProtoReflect.Descriptor instead.
func (*TopicSummary) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{25}
}

func (x *TopicSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicSummary) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *TopicSummary) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *TopicSummary) GetConsumerCount() uint64 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *TopicSummary) GetDlqCount() uint64 {
	if x != nil {
		return x.DlqCount
	}
	return 0
}

func (x *TopicSummary) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *TopicSummary) GetAckPendingCount() uint64 {
	if x != nil {
		return x.AckPendingCount
	}
	return 0
}

func (x *TopicSummary) GetFirstSequence() uint64 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *TopicSummary) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

func (x *TopicSummary) GetLatestEventAt() string {
	if x != nil {
		return x.LatestEventAt
	}
	return ""
}

func (x *TopicSummary) GetHealth() ExplorerHealthStatus {
	if x != nil {
		return x.Health
	}
	return ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_UNSPECIFIED
}

func (x *TopicSummary) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

// Request to list partitions for a topic.
type ListPartitionsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Topic         string                   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Pagination    *OffsetPaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_explorer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{26}
}

func (x *ListPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ListPartitionsRequest) GetPagination() *OffsetPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Response containing a page of partitions.
type ListPartitionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*PartitionSummary       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *OffsetPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_explorer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{27}
}

func (x *ListPartitionsResponse) GetData() []*PartitionSummary {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPartitionsResponse) GetPagination() *OffsetPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Summary information for a partition.
type PartitionSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageCount    uint64                 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Topic           string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	PendingCount    uint64                 `protobuf:"varint,4,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	AckPendingCount uint64                 `protobuf:"varint,5,opt,name=ack_pending_count,json=ackPendingCount,proto3" json:"ack_pending_count,omitempty"`
	FirstSequence   uint64                 `protobuf:"varint,6,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	LatestSequence  uint64                 `protobuf:"varint,7,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	LatestEventAt   string                 `protobuf:"bytes,8,opt,name=latest_event_at,json=latestEventAt,proto3" json:"latest_event_at,omitempty"`
	Health          ExplorerHealthStatus   `protobuf:"varint,9,opt,name=health,proto3,enum=cdc.v1.ExplorerHealthStatus" json:"health,omitempty"`
	Partial         bool                   `protobuf:"varint,10,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionSummary) Reset() {
	*x = PartitionSummary{}
	mi := &file_explorer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionSummary) ProtoMessage() {}

func (x *PartitionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionSummary.ProtoReflect.Descriptor instead.
func (*PartitionSummary) Descriptor() ([]byte, []int) {
	return file_explorer_proto_rawDescGZIP(), []int{28}
}

func (x *PartitionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartitionSummary) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *PartitionSummary) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionSummary) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *PartitionSummary) GetAckPendingCount() uint64 {
	if x != nil {
		return x.AckPendingCount
	}
	return 0
}

func (x *PartitionSummary) GetFirstSequence() uint64 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *PartitionSummary) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

func (x *PartitionSummary) GetLatestEventAt() string {
	if x != nil {
		return x.LatestEventAt
	}
	return ""
}

func (x *PartitionSummary) GetHealth() ExplorerHealthStatus {
	if x != nil {
		return x.Health
	}
	return ExplorerHealthStatus_EXPLORER_HEALTH_STATUS_UNSPECIFIED
}

func (x *PartitionSummary) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

var File_explorer_proto protoreflect.FileDescriptor

const file_explorer_proto_rawDesc = "" +
	"\n" +
	"\x0eexplorer.proto\x12\x06cdc.v1\x1a\fcommon.proto\"\xbb\x01\n" +
	"\x14ExplorerScanMetadata\x12\x18\n" +
	"\apartial\x18\x01 \x01(\bR\apartial\x12$\n" +
	"\x0escan_limit_hit\x18\x02 \x01(\bR\fscanLimitHit\x12#\n" +
	"\rscanned_count\x18\x03 \x01(\x04R\fscannedCount\x12#\n" +
	"\rmatched_count\x18\x04 \x01(\x04R\fmatchedCount\x12\x19\n" +
	"\bmax_scan\x18\x05 \x01(\x04R\amaxScan\"\xeb\a\n" +
	"\x13ListMessagesRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.cdc.v1.MessageStatusR\x06status\x12 \n" +
	"\tsource_id\x18\x02 \x01(\tH\x00R\bsourceId\x88\x01\x01\x12\x19\n" +
	"\x05topic\x18\x03 \x01(\tH\x01R\x05topic\x88\x01\x01\x12!\n" +
	"\tpartition\x18\x04 \x01(\tH\x02R\tpartition\x88\x01\x01\x12?\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x1f.cdc.v1.OffsetPaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\x06schema\x18\x06 \x01(\tH\x03R\x06schema\x88\x01\x01\x12\x19\n" +
	"\x05table\x18\a \x01(\tH\x04R\x05table\x88\x01\x01\x12\x13\n" +
	"\x02op\x18\b \x01(\tH\x05R\x02op\x88\x01\x01\x12&\n" +
	"\fsequence_min\x18\t \x01(\x04H\x06R\vsequenceMin\x88\x01\x01\x12&\n" +
	"\fsequence_max\x18\n" +
	" \x01(\x04H\aR\vsequenceMax\x88\x01\x01\x12*\n" +
	"\x0etimestamp_from\x18\v \x01(\x03H\bR\rtimestampFrom\x88\x01\x01\x12&\n" +
	"\ftimestamp_to\x18\f \x01(\x03H\tR\vtimestampTo\x88\x01\x01\x12\"\n" +
	"\n" +
	"header_key\x18\r \x01(\tH\n" +
	"R\theaderKey\x88\x01\x01\x12&\n" +
	"\fheader_value\x18\x0e \x01(\tH\vR\vheaderValue\x88\x01\x01\x12 \n" +
	"\tjson_path\x18\x0f \x01(\tH\fR\bjsonPath\x88\x01\x01\x12$\n" +
	"\vjson_equals\x18\x10 \x01(\tH\rR\n" +
	"jsonEquals\x88\x01\x01\x12(\n" +
	"\rtext_contains\x18\x11 \x01(\tH\x0eR\ftextContains\x88\x01\x01\x12)\n" +
	"\x10reprocessed_only\x18\x12 \x01(\bR\x0freprocessedOnly\x12(\n" +
	"\x10dlq_related_only\x18\x13 \x01(\bR\x0edlqRelatedOnly\x12(\n" +
	"\x04sort\x18\x14 \x01(\x0e2\x14.cdc.v1.ExplorerSortR\x04sortB\f\n" +
	"\n" +
	"_source_idB\b\n" +
	"\x06_topicB\f\n" +
	"\n" +
	"_partitionB\t\n" +
	"\a_schemaB\b\n" +
	"\x06_tableB\x05\n" +
	"\x03_opB\x0f\n" +
	"\r_sequence_minB\x0f\n" +
	"\r_sequence_maxB\x11\n" +
	"\x0f_timestamp_fromB\x0f\n" +
	"\r_timestamp_toB\r\n" +
	"\v_header_keyB\x0f\n" +
	"\r_header_valueB\f\n" +
	"\n" +
	"_json_pathB\x0e\n" +
	"\f_json_equalsB\x10\n" +
	"\x0e_text_contains\"\xd4\x01\n" +
	"\x14ListMessagesResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.cdc.v1.MessageItemR\x04data\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12@\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2 .cdc.v1.OffsetPaginationResponseR\n" +
	"pagination\x120\n" +
	"\x04scan\x18\x04 \x01(\v2\x1c.cdc.v1.ExplorerScanMetadataR\x04scan\"\xa3\x04\n" +
	"\vMessageItem\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12:\n" +
	"\aheaders\x18\x05 \x03(\v2 .cdc.v1.MessageItem.HeadersEntryR\aheaders\x12\x0e\n" +
	"\x02op\x18\x06 \x01(\tR\x02op\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\tR\bsourceId\x12\x16\n" +
	"\x06schema\x18\b \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\t \x01(\tR\x05table\x12\x1c\n" +
	"\tpartition\x18\n" +
	" \x01(\tR\tpartition\x12\x10\n" +
	"\x03key\x18\v \x01(\tR\x03key\x12!\n" +
	"\fpayload_size\x18\f \x01(\x04R\vpayloadSize\x12!\n" +
	"\fheader_count\x18\r \x01(\rR\vheaderCount\x12\x1e\n" +
	"\vnats_msg_id\x18\x0e \x01(\tR\tnatsMsgId\x12)\n" +
	"\x10reprocessed_from\x18\x0f \x01(\tR\x0freprocessedFrom\x12\x18\n" +
	"\amarkers\x18\x10 \x03(\tR\amarkers\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\x1aGetExplorerOverviewRequest\"\x86\x03\n" +
	"\x1bGetExplorerOverviewResponse\x12\x1f\n" +
	"\vtopic_count\x18\x01 \x01(\x04R\n" +
	"topicCount\x12'\n" +
	"\x0fpartition_count\x18\x02 \x01(\x04R\x0epartitionCount\x12%\n" +
	"\x0econsumer_count\x18\x03 \x01(\x04R\rconsumerCount\x12#\n" +
	"\rpending_count\x18\x04 \x01(\x04R\fpendingCount\x12*\n" +
	"\x11ack_pending_count\x18\x05 \x01(\x04R\x0fackPendingCount\x12\x1b\n" +
	"\tdlq_depth\x18\x06 \x01(\x04R\bdlqDepth\x12N\n" +
	"\x18topics_needing_attention\x18\a \x03(\v2\x14.cdc.v1.TopicSummaryR\x16topicsNeedingAttention\x128\n" +
	"\n" +
	"recent_dlq\x18\b \x03(\v2\x19.cdc.v1.DLQMessageSummaryR\trecentDlq\"-\n" +
	"\x15GetTopicDetailRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\xb4\x01\n" +
	"\x16GetTopicDetailResponse\x12.\n" +
	"\asummary\x18\x01 \x01(\v2\x14.cdc.v1.TopicSummaryR\asummary\x128\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x18.cdc.v1.PartitionSummaryR\n" +
	"partitions\x120\n" +
	"\x04scan\x18\x03 \x01(\v2\x1c.cdc.v1.ExplorerScanMetadataR\x04scan\"O\n" +
	"\x19GetPartitionDetailRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\"\xfd\x01\n" +
	"\x1aGetPartitionDetailResponse\x122\n" +
	"\asummary\x18\x01 \x01(\v2\x18.cdc.v1.PartitionSummaryR\asummary\x12<\n" +
	"\x0frecent_messages\x18\x02 \x03(\v2\x13.cdc.v1.MessageItemR\x0erecentMessages\x12;\n" +
	"\vcheckpoints\x18\x03 \x03(\v2\x19.cdc.v1.CheckpointContextR\vcheckpoints\x120\n" +
	"\x04scan\x18\x04 \x01(\v2\x1c.cdc.v1.ExplorerScanMetadataR\x04scan\"\xd2\a\n" +
	"\x1cListPartitionMessagesRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.cdc.v1.MessageStatusR\x06status\x12 \n" +
	"\tsource_id\x18\x02 \x01(\tH\x00R\bsourceId\x88\x01\x01\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\tR\tpartition\x12?\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x1f.cdc.v1.OffsetPaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\x06schema\x18\x06 \x01(\tH\x01R\x06schema\x88\x01\x01\x12\x19\n" +
	"\x05table\x18\a \x01(\tH\x02R\x05table\x88\x01\x01\x12\x13\n" +
	"\x02op\x18\b \x01(\tH\x03R\x02op\x88\x01\x01\x12&\n" +
	"\fsequence_min\x18\t \x01(\x04H\x04R\vsequenceMin\x88\x01\x01\x12&\n" +
	"\fsequence_max\x18\n" +
	" \x01(\x04H\x05R\vsequenceMax\x88\x01\x01\x12*\n" +
	"\x0etimestamp_from\x18\v \x01(\x03H\x06R\rtimestampFrom\x88\x01\x01\x12&\n" +
	"\ftimestamp_to\x18\f \x01(\x03H\aR\vtimestampTo\x88\x01\x01\x12\"\n" +
	"\n" +
	"header_key\x18\r \x01(\tH\bR\theaderKey\x88\x01\x01\x12&\n" +
	"\fheader_value\x18\x0e \x01(\tH\tR\vheaderValue\x88\x01\x01\x12 \n" +
	"\tjson_path\x18\x0f \x01(\tH\n" +
	"R\bjsonPath\x88\x01\x01\x12$\n" +
	"\vjson_equals\x18\x10 \x01(\tH\vR\n" +
	"jsonEquals\x88\x01\x01\x12(\n" +
	"\rtext_contains\x18\x11 \x01(\tH\fR\ftextContains\x88\x01\x01\x12)\n" +
	"\x10reprocessed_only\x18\x12 \x01(\bR\x0freprocessedOnly\x12(\n" +
	"\x10dlq_related_only\x18\x13 \x01(\bR\x0edlqRelatedOnly\x12(\n" +
	"\x04sort\x18\x14 \x01(\x0e2\x14.cdc.v1.ExplorerSortR\x04sortB\f\n" +
	"\n" +
	"_source_idB\t\n" +
	"\a_schemaB\b\n" +
	"\x06_tableB\x05\n" +
	"\x03_opB\x0f\n" +
	"\r_sequence_minB\x0f\n" +
	"\r_sequence_maxB\x11\n" +
	"\x0f_timestamp_fromB\x0f\n" +
	"\r_timestamp_toB\r\n" +
	"\v_header_keyB\x0f\n" +
	"\r_header_valueB\f\n" +
	"\n" +
	"_json_pathB\x0e\n" +
	"\f_json_equalsB\x10\n" +
	"\x0e_text_contains\"\xdd\x01\n" +
	"\x1dListPartitionMessagesResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.cdc.v1.MessageItemR\x04data\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12@\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2 .cdc.v1.OffsetPaginationResponseR\n" +
	"pagination\x120\n" +
	"\x04scan\x18\x04 \x01(\v2\x1c.cdc.v1.ExplorerScanMetadataR\x04scan\"i\n" +
	"\x17GetMessageDetailRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\xd3\x01\n" +
	"\x18GetMessageDetailResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.cdc.v1.MessageItemR\x04item\x12\x16\n" +
	"\x06before\x18\x02 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\x03 \x01(\fR\x05after\x12%\n" +
	"\x0echanged_fields\x18\x04 \x03(\tR\rchangedFields\x129\n" +
	"\n" +
	"checkpoint\x18\x05 \x01(\v2\x19.cdc.v1.CheckpointContextR\n" +
	"checkpoint\"\xd3\x02\n" +
	"\x11CheckpointContext\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x120\n" +
	"\x14delivered_stream_seq\x18\x02 \x01(\x04R\x12deliveredStreamSeq\x12/\n" +
	"\x14ack_floor_stream_seq\x18\x03 \x01(\x04R\x11ackFloorStreamSeq\x12\x1f\n" +
	"\vnum_pending\x18\x04 \x01(\x04R\n" +
	"numPending\x12&\n" +
	"\x0fnum_ack_pending\x18\x05 \x01(\x04R\rnumAckPending\x12!\n" +
	"\flag_messages\x18\x06 \x01(\x04R\vlagMessages\x12*\n" +
	"\x11last_delivered_at\x18\a \x01(\tR\x0flastDeliveredAt\x12\x1e\n" +
	"\vlast_ack_at\x18\b \x01(\tR\tlastAckAt\"\xac\x01\n" +
	"\x11DLQMessageSummary\x12\x15\n" +
	"\x06dlq_id\x18\x01 \x01(\tR\x05dlqId\x12)\n" +
	"\x10original_subject\x18\x02 \x01(\tR\x0foriginalSubject\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1f\n" +
	"\verror_class\x18\x04 \x01(\tR\n" +
	"errorClass\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"=\n" +
	"\x16GetConsumerInfoRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\"[\n" +
	"\x17GetConsumerInfoResponse\x12\x1b\n" +
	"\tack_floor\x18\x01 \x01(\x04R\backFloor\x12#\n" +
	"\rpending_count\x18\x02 \x01(\x04R\fpendingCount\"\x8a\x03\n" +
	"\x0fConsumerSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0ffilter_subjects\x18\x02 \x03(\tR\x0efilterSubjects\x12\x1f\n" +
	"\vnum_pending\x18\x03 \x01(\x04R\n" +
	"numPending\x12&\n" +
	"\x0fnum_ack_pending\x18\x04 \x01(\x04R\rnumAckPending\x120\n" +
	"\x14delivered_stream_seq\x18\x05 \x01(\x04R\x12deliveredStreamSeq\x12/\n" +
	"\x14ack_floor_stream_seq\x18\x06 \x01(\x04R\x11ackFloorStreamSeq\x12!\n" +
	"\flag_messages\x18\a \x01(\x04R\vlagMessages\x12\x1f\n" +
	"\vreplay_risk\x18\b \x01(\tR\n" +
	"replayRisk\x12*\n" +
	"\x11last_delivered_at\x18\t \x01(\tR\x0flastDeliveredAt\x12\x1e\n" +
	"\vlast_ack_at\x18\n" +
	" \x01(\tR\tlastAckAt\"?\n" +
	"\x18GetConsumerDetailRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\"\xa6\x02\n" +
	"\x19GetConsumerDetailResponse\x121\n" +
	"\asummary\x18\x01 \x01(\v2\x17.cdc.v1.ConsumerSummaryR\asummary\x12,\n" +
	"\x06topics\x18\x02 \x03(\v2\x14.cdc.v1.TopicSummaryR\x06topics\x128\n" +
	"\n" +
	"partitions\x18\x03 \x03(\v2\x18.cdc.v1.PartitionSummaryR\n" +
	"partitions\x12<\n" +
	"\x0frecent_messages\x18\x04 \x03(\v2\x13.cdc.v1.MessageItemR\x0erecentMessages\x120\n" +
	"\x04scan\x18\x05 \x01(\v2\x1c.cdc.v1.ExplorerScanMetadataR\x04scan\"W\n" +
	"\x14ListConsumersRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.cdc.v1.OffsetPaginationRequestR\n" +
	"pagination\"\x86\x01\n" +
	"\x15ListConsumersResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.cdc.v1.ConsumerSummaryR\x04data\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .cdc.v1.OffsetPaginationResponseR\n" +
	"pagination\"T\n" +
	"\x11ListTopicsRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.cdc.v1.OffsetPaginationRequestR\n" +
	"pagination\"\x80\x01\n" +
	"\x12ListTopicsResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.cdc.v1.TopicSummaryR\x04data\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .cdc.v1.OffsetPaginationResponseR\n" +
	"pagination\"\xcd\x03\n" +
	"\fTopicSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x04R\fmessageCount\x12'\n" +
	"\x0fpartition_count\x18\x03 \x01(\x05R\x0epartitionCount\x12%\n" +
	"\x0econsumer_count\x18\x04 \x01(\x04R\rconsumerCount\x12\x1b\n" +
	"\tdlq_count\x18\x05 \x01(\x04R\bdlqCount\x12#\n" +
	"\rpending_count\x18\x06 \x01(\x04R\fpendingCount\x12*\n" +
	"\x11ack_pending_count\x18\a \x01(\x04R\x0fackPendingCount\x12%\n" +
	"\x0efirst_sequence\x18\b \x01(\x04R\rfirstSequence\x12'\n" +
	"\x0flatest_sequence\x18\t \x01(\x04R\x0elatestSequence\x12&\n" +
	"\x0flatest_event_at\x18\n" +
	" \x01(\tR\rlatestEventAt\x124\n" +
	"\x06health\x18\v \x01(\x0e2\x1c.cdc.v1.ExplorerHealthStatusR\x06health\x12\x18\n" +
	"\apartial\x18\f \x01(\bR\apartial\"n\n" +
	"\x15ListPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.cdc.v1.OffsetPaginationRequestR\n" +
	"pagination\"\x88\x01\n" +
	"\x16ListPartitionsResponse\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.cdc.v1.PartitionSummaryR\x04data\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .cdc.v1.OffsetPaginationResponseR\n" +
	"pagination\"\xf6\x02\n" +
	"\x10PartitionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x04R\fmessageCount\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12#\n" +
	"\rpending_count\x18\x04 \x01(\x04R\fpendingCount\x12*\n" +
	"\x11ack_pending_count\x18\x05 \x01(\x04R\x0fackPendingCount\x12%\n" +
	"\x0efirst_sequence\x18\x06 \x01(\x04R\rfirstSequence\x12'\n" +
	"\x0flatest_sequence\x18\a \x01(\x04R\x0elatestSequence\x12&\n" +
	"\x0flatest_event_at\x18\b \x01(\tR\rlatestEventAt\x124\n" +
	"\x06health\x18\t \x01(\x0e2\x1c.cdc.v1.ExplorerHealthStatusR\x06health\x12\x18\n" +
	"\apartial\x18\n" +
	" \x01(\bR\apartial*c\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x19\n" +
	"\x15MESSAGE_STATUS_UNSENT\x10\x02*\xe9\x01\n" +
	"\x14ExplorerHealthStatus\x12&\n" +
	"\"EXPLORER_HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eEXPLORER_HEALTH_STATUS_HEALTHY\x10\x01\x12\x1f\n" +
	"\x1bEXPLORER_HEALTH_STATUS_IDLE\x10\x02\x12\"\n" +
	"\x1eEXPLORER_HEALTH_STATUS_LAGGING\x10\x03\x12 \n" +
	"\x1cEXPLORER_HEALTH_STATUS_STALE\x10\x04\x12\x1e\n" +
	"\x1aEXPLORER_HEALTH_STATUS_DLQ\x10\x05*m\n" +
	"\fExplorerSort\x12\x1d\n" +
	"\x19EXPLORER_SORT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEXPLORER_SORT_NEWEST_FIRST\x10\x01\x12\x1e\n" +
	"\x1aEXPLORER_SORT_OLDEST_FIRST\x10\x02B)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_explorer_proto_rawDescOnce sync.Once
	file_explorer_proto_rawDescData []byte
)

func file_explorer_proto_rawDescGZIP() []byte {
	file_explorer_proto_rawDescOnce.Do(func() {
		file_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)))
	})
	return file_explorer_proto_rawDescData
}

var file_explorer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_explorer_proto_goTypes = []any{
	(MessageStatus)(0),                    // 0: cdc.v1.MessageStatus
	(ExplorerHealthStatus)(0),             // 1: cdc.v1.ExplorerHealthStatus
	(ExplorerSort)(0),                     // 2: cdc.v1.ExplorerSort
	(*ExplorerScanMetadata)(nil),          // 3: cdc.v1.ExplorerScanMetadata
	(*ListMessagesRequest)(nil),           // 4: cdc.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),          // 5: cdc.v1.ListMessagesResponse
	(*MessageItem)(nil),                   // 6: cdc.v1.MessageItem
	(*GetExplorerOverviewRequest)(nil),    // 7: cdc.v1.GetExplorerOverviewRequest
	(*GetExplorerOverviewResponse)(nil),   // 8: cdc.v1.GetExplorerOverviewResponse
	(*GetTopicDetailRequest)(nil),         // 9: cdc.v1.GetTopicDetailRequest
	(*GetTopicDetailResponse)(nil),        // 10: cdc.v1.GetTopicDetailResponse
	(*GetPartitionDetailRequest)(nil),     // 11: cdc.v1.GetPartitionDetailRequest
	(*GetPartitionDetailResponse)(nil),    // 12: cdc.v1.GetPartitionDetailResponse
	(*ListPartitionMessagesRequest)(nil),  // 13: cdc.v1.ListPartitionMessagesRequest
	(*ListPartitionMessagesResponse)(nil), // 14: cdc.v1.ListPartitionMessagesResponse
	(*GetMessageDetailRequest)(nil),       // 15: cdc.v1.GetMessageDetailRequest
	(*GetMessageDetailResponse)(nil),      // 16: cdc.v1.GetMessageDetailResponse
	(*CheckpointContext)(nil),             // 17: cdc.v1.CheckpointContext
	(*DLQMessageSummary)(nil),             // 18: cdc.v1.DLQMessageSummary
	(*GetConsumerInfoRequest)(nil),        // 19: cdc.v1.GetConsumerInfoRequest
	(*GetConsumerInfoResponse)(nil),       // 20: cdc.v1.GetConsumerInfoResponse
	(*ConsumerSummary)(nil),               // 21: cdc.v1.ConsumerSummary
	(*GetConsumerDetailRequest)(nil),      // 22: cdc.v1.GetConsumerDetailRequest
	(*GetConsumerDetailResponse)(nil),     // 23: cdc.v1.GetConsumerDetailResponse
	(*ListConsumersRequest)(nil),          // 24: cdc.v1.ListConsumersRequest
	(*ListConsumersResponse)(nil),         // 25: cdc.v1.ListConsumersResponse
	(*ListTopicsRequest)(nil),             // 26: cdc.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),            // 27: cdc.v1.ListTopicsResponse
	(*TopicSummary)(nil),                  // 28: cdc.v1.TopicSummary
	(*ListPartitionsRequest)(nil),         // 29: cdc.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),        // 30: cdc.v1.ListPartitionsResponse
	(*PartitionSummary)(nil),              // 31: cdc.v1.PartitionSummary
	nil,                                   // 32: cdc.v1.MessageItem.HeadersEntry
	(*OffsetPaginationRequest)(nil),       // 33: cdc.v1.OffsetPaginationRequest
	(*OffsetPaginationResponse)(nil),      // 34: cdc.v1.OffsetPaginationResponse
}
var file_explorer_proto_depIdxs = []int32{
	0,  // 0: cdc.v1.ListMessagesRequest.status:type_name -> cdc.v1.MessageStatus
	33, // 1: cdc.v1.ListMessagesRequest.pagination:type_name -> cdc.v1.OffsetPaginationRequest
	2,  // 2: cdc.v1.ListMessagesRequest.sort:type_name -> cdc.v1.ExplorerSort
	6,  // 3: cdc.v1.ListMessagesResponse.data:type_name -> cdc.v1.MessageItem
	34, // 4: cdc.v1.ListMessagesResponse.pagination:type_name -> cdc.v1.OffsetPaginationResponse
	3,  // 5: cdc.v1.ListMessagesResponse.scan:type_name -> cdc.v1.ExplorerScanMetadata
	32, // 6: cdc.v1.MessageItem.headers:type_name -> cdc.v1.MessageItem.HeadersEntry
	28, // 7: cdc.v1.GetExplorerOverviewResponse.topics_needing_attention:type_name -> cdc.v1.TopicSummary
	18, // 8: cdc.v1.GetExplorerOverviewResponse.recent_dlq:type_name -> cdc.v1.DLQMessageSummary
	28, // 9: cdc.v1.GetTopicDetailResponse.summary:type_name -> cdc.v1.TopicSummary
	31, // 10: cdc.v1.GetTopicDetailResponse.partitions:type_name -> cdc.v1.PartitionSummary
	3,  // 11: cdc.v1.GetTopicDetailResponse.scan:type_name -> cdc.v1.ExplorerScanMetadata
	31, // 12: cdc.v1.GetPartitionDetailResponse.summary:type_name -> cdc.v1.PartitionSummary
	6,  // 13: cdc.v1.GetPartitionDetailResponse.recent_messages:type_name -> cdc.v1.MessageItem
	17, // 14: cdc.v1.GetPartitionDetailResponse.checkpoints:type_name -> cdc.v1.CheckpointContext
	3,  // 15: cdc.v1.GetPartitionDetailResponse.scan:type_name -> cdc.v1.ExplorerScanMetadata
	0,  // 16: cdc.v1.ListPartitionMessagesRequest.status:type_name -> cdc.v1.MessageStatus
	33, // 17: cdc.v1.ListPartitionMessagesRequest.pagination:type_name -> cdc.v1.OffsetPaginationRequest
	2,  // 18: cdc.v1.ListPartitionMessagesRequest.sort:type_name -> cdc.v1.ExplorerSort
	6,  // 19: cdc.v1.ListPartitionMessagesResponse.data:type_name -> cdc.v1.MessageItem
	34, // 20: cdc.v1.ListPartitionMessagesResponse.pagination:type_name -> cdc.v1.OffsetPaginationResponse
	3,  // 21: cdc.v1.ListPartitionMessagesResponse.scan:type_name -> cdc.v1.ExplorerScanMetadata
	6,  // 22: cdc.v1.GetMessageDetailResponse.item:type_name -> cdc.v1.MessageItem
	17, // 23: cdc.v1.GetMessageDetailResponse.checkpoint:type_name -> cdc.v1.CheckpointContext
	21, // 24: cdc.v1.GetConsumerDetailResponse.summary:type_name -> cdc.v1.ConsumerSummary
	28, // 25: cdc.v1.GetConsumerDetailResponse.topics:type_name -> cdc.v1.TopicSummary
	31, // 26: cdc.v1.GetConsumerDetailResponse.partitions:type_name -> cdc.v1.PartitionSummary
	6,  // 27: cdc.v1.GetConsumerDetailResponse.recent_messages:type_name -> cdc.v1.MessageItem
	3,  // 28: cdc.v1.GetConsumerDetailResponse.scan:type_name -> cdc.v1.ExplorerScanMetadata
	33, // 29: cdc.v1.ListConsumersRequest.pagination:type_name -> cdc.v1.OffsetPaginationRequest
	21, // 30: cdc.v1.ListConsumersResponse.data:type_name -> cdc.v1.ConsumerSummary
	34, // 31: cdc.v1.ListConsumersResponse.pagination:type_name -> cdc.v1.OffsetPaginationResponse
	33, // 32: cdc.v1.ListTopicsRequest.pagination:type_name -> cdc.v1.OffsetPaginationRequest
	28, // 33: cdc.v1.ListTopicsResponse.data:type_name -> cdc.v1.TopicSummary
	34, // 34: cdc.v1.ListTopicsResponse.pagination:type_name -> cdc.v1.OffsetPaginationResponse
	1,  // 35: cdc.v1.TopicSummary.health:type_name -> cdc.v1.ExplorerHealthStatus
	33, // 36: cdc.v1.ListPartitionsRequest.pagination:type_name -> cdc.v1.OffsetPaginationRequest
	31, // 37: cdc.v1.ListPartitionsResponse.data:type_name -> cdc.v1.PartitionSummary
	34, // 38: cdc.v1.ListPartitionsResponse.pagination:type_name -> cdc.v1.OffsetPaginationResponse
	1,  // 39: cdc.v1.PartitionSummary.health:type_name -> cdc.v1.ExplorerHealthStatus
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_explorer_proto_init() }
func file_explorer_proto_init() {
	if File_explorer_proto != nil {
		return
	}
	file_common_proto_init()
	file_explorer_proto_msgTypes[1].OneofWrappers = []any{}
	file_explorer_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explorer_proto_rawDesc), len(file_explorer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_explorer_proto_goTypes,
		DependencyIndexes: file_explorer_proto_depIdxs,
		EnumInfos:         file_explorer_proto_enumTypes,
		MessageInfos:      file_explorer_proto_msgTypes,
	}.Build()
	File_explorer_proto = out.File
	file_explorer_proto_goTypes = nil
	file_explorer_proto_depIdxs = nil
}
