// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: metrics.proto

package cdcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get stats request (empty).
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

// Get stats response with source and sink statistics.
type GetStatsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SourceStats   map[string]*ComponentStats `protobuf:"bytes,1,rep,name=source_stats,json=sourceStats,proto3" json:"source_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SinkStats     map[string]*ComponentStats `protobuf:"bytes,2,rep,name=sink_stats,json=sinkStats,proto3" json:"sink_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetSourceStats() map[string]*ComponentStats {
	if x != nil {
		return x.SourceStats
	}
	return nil
}

func (x *GetStatsResponse) GetSinkStats() map[string]*ComponentStats {
	if x != nil {
		return x.SinkStats
	}
	return nil
}

// Statistics for a single component (source or sink).
type ComponentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  uint64                 `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  uint64                 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	LastError     string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	PartitionLag  map[int32]uint64       `protobuf:"bytes,4,rep,name=partition_lag,json=partitionLag,proto3" json:"partition_lag,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastEventAt   int64                  `protobuf:"varint,5,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	ActiveFlows   int32                  `protobuf:"varint,6,opt,name=active_flows,json=activeFlows,proto3" json:"active_flows,omitempty"`
	Throughput    float64                `protobuf:"fixed64,7,opt,name=throughput,proto3" json:"throughput,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,8,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	AvgLatencyMs  int64                  `protobuf:"varint,9,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentStats) Reset() {
	*x = ComponentStats{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStats) ProtoMessage() {}

func (x *ComponentStats) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStats.ProtoReflect.Descriptor instead.
func (*ComponentStats) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentStats) GetSuccessCount() uint64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ComponentStats) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ComponentStats) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ComponentStats) GetPartitionLag() map[int32]uint64 {
	if x != nil {
		return x.PartitionLag
	}
	return nil
}

func (x *ComponentStats) GetLastEventAt() int64 {
	if x != nil {
		return x.LastEventAt
	}
	return 0
}

func (x *ComponentStats) GetActiveFlows() int32 {
	if x != nil {
		return x.ActiveFlows
	}
	return 0
}

func (x *ComponentStats) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *ComponentStats) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ComponentStats) GetAvgLatencyMs() int64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x06cdc.v1\"\x11\n" +
	"\x0fGetStatsRequest\"\xd6\x02\n" +
	"\x10GetStatsResponse\x12L\n" +
	"\fsource_stats\x18\x01 \x03(\v2).cdc.v1.GetStatsResponse.SourceStatsEntryR\vsourceStats\x12F\n" +
	"\n" +
	"sink_stats\x18\x02 \x03(\v2'.cdc.v1.GetStatsResponse.SinkStatsEntryR\tsinkStats\x1aV\n" +
	"\x10SourceStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.cdc.v1.ComponentStatsR\x05value:\x028\x01\x1aT\n" +
	"\x0eSinkStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.cdc.v1.ComponentStatsR\x05value:\x028\x01\"\xb5\x03\n" +
	"\x0eComponentStats\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x04R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x04R\ffailureCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12M\n" +
	"\rpartition_lag\x18\x04 \x03(\v2(.cdc.v1.ComponentStats.PartitionLagEntryR\fpartitionLag\x12\"\n" +
	"\rlast_event_at\x18\x05 \x01(\x03R\vlastEventAt\x12!\n" +
	"\factive_flows\x18\x06 \x01(\x05R\vactiveFlows\x12\x1e\n" +
	"\n" +
	"throughput\x18\a \x01(\x01R\n" +
	"throughput\x12\x1d\n" +
	"\n" +
	"error_rate\x18\b \x01(\x01R\terrorRate\x12$\n" +
	"\x0eavg_latency_ms\x18\t \x01(\x03R\favgLatencyMs\x1a?\n" +
	"\x11PartitionLagEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metrics_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: cdc.v1.GetStatsRequest
	(*GetStatsResponse)(nil), // 1: cdc.v1.GetStatsResponse
	(*ComponentStats)(nil),   // 2: cdc.v1.ComponentStats
	nil,                      // 3: cdc.v1.GetStatsResponse.SourceStatsEntry
	nil,                      // 4: cdc.v1.GetStatsResponse.SinkStatsEntry
	nil,                      // 5: cdc.v1.ComponentStats.PartitionLagEntry
}
var file_metrics_proto_depIdxs = []int32{
	3, // 0: cdc.v1.GetStatsResponse.source_stats:type_name -> cdc.v1.GetStatsResponse.SourceStatsEntry
	4, // 1: cdc.v1.GetStatsResponse.sink_stats:type_name -> cdc.v1.GetStatsResponse.SinkStatsEntry
	5, // 2: cdc.v1.ComponentStats.partition_lag:type_name -> cdc.v1.ComponentStats.PartitionLagEntry
	2, // 3: cdc.v1.GetStatsResponse.SourceStatsEntry.value:type_name -> cdc.v1.ComponentStats
	2, // 4: cdc.v1.GetStatsResponse.SinkStatsEntry.value:type_name -> cdc.v1.ComponentStats
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
