// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: service.proto

package cdcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CDCService_HealthCheck_FullMethodName           = "/cdc.v1.CDCService/HealthCheck"
	CDCService_GetStats_FullMethodName              = "/cdc.v1.CDCService/GetStats"
	CDCService_GetDashboardSummary_FullMethodName   = "/cdc.v1.CDCService/GetDashboardSummary"
	CDCService_CreateSource_FullMethodName          = "/cdc.v1.CDCService/CreateSource"
	CDCService_GetSource_FullMethodName             = "/cdc.v1.CDCService/GetSource"
	CDCService_ListSources_FullMethodName           = "/cdc.v1.CDCService/ListSources"
	CDCService_DeleteSource_FullMethodName          = "/cdc.v1.CDCService/DeleteSource"
	CDCService_TestSourceConnection_FullMethodName  = "/cdc.v1.CDCService/TestSourceConnection"
	CDCService_CreateSink_FullMethodName            = "/cdc.v1.CDCService/CreateSink"
	CDCService_GetSink_FullMethodName               = "/cdc.v1.CDCService/GetSink"
	CDCService_ListSinks_FullMethodName             = "/cdc.v1.CDCService/ListSinks"
	CDCService_DeleteSink_FullMethodName            = "/cdc.v1.CDCService/DeleteSink"
	CDCService_TestSinkConnection_FullMethodName    = "/cdc.v1.CDCService/TestSinkConnection"
	CDCService_CreateFlow_FullMethodName            = "/cdc.v1.CDCService/CreateFlow"
	CDCService_GetFlow_FullMethodName               = "/cdc.v1.CDCService/GetFlow"
	CDCService_ListFlows_FullMethodName             = "/cdc.v1.CDCService/ListFlows"
	CDCService_UpdateFlow_FullMethodName            = "/cdc.v1.CDCService/UpdateFlow"
	CDCService_DeleteFlow_FullMethodName            = "/cdc.v1.CDCService/DeleteFlow"
	CDCService_PauseFlow_FullMethodName             = "/cdc.v1.CDCService/PauseFlow"
	CDCService_ResumeFlow_FullMethodName            = "/cdc.v1.CDCService/ResumeFlow"
	CDCService_GetFlowStats_FullMethodName          = "/cdc.v1.CDCService/GetFlowStats"
	CDCService_DiscoverTables_FullMethodName        = "/cdc.v1.CDCService/DiscoverTables"
	CDCService_DiscoverSinkTables_FullMethodName    = "/cdc.v1.CDCService/DiscoverSinkTables"
	CDCService_GetExplorerOverview_FullMethodName   = "/cdc.v1.CDCService/GetExplorerOverview"
	CDCService_ListMessages_FullMethodName          = "/cdc.v1.CDCService/ListMessages"
	CDCService_GetTopicDetail_FullMethodName        = "/cdc.v1.CDCService/GetTopicDetail"
	CDCService_GetPartitionDetail_FullMethodName    = "/cdc.v1.CDCService/GetPartitionDetail"
	CDCService_ListPartitionMessages_FullMethodName = "/cdc.v1.CDCService/ListPartitionMessages"
	CDCService_GetMessageDetail_FullMethodName      = "/cdc.v1.CDCService/GetMessageDetail"
	CDCService_GetConsumerInfo_FullMethodName       = "/cdc.v1.CDCService/GetConsumerInfo"
	CDCService_ListConsumers_FullMethodName         = "/cdc.v1.CDCService/ListConsumers"
	CDCService_GetConsumerDetail_FullMethodName     = "/cdc.v1.CDCService/GetConsumerDetail"
	CDCService_ListTopics_FullMethodName            = "/cdc.v1.CDCService/ListTopics"
	CDCService_ListPartitions_FullMethodName        = "/cdc.v1.CDCService/ListPartitions"
	CDCService_ListDLQMessages_FullMethodName       = "/cdc.v1.CDCService/ListDLQMessages"
	CDCService_PreviewDLQReprocess_FullMethodName   = "/cdc.v1.CDCService/PreviewDLQReprocess"
	CDCService_ReprocessDLQ_FullMethodName          = "/cdc.v1.CDCService/ReprocessDLQ"
)

// CDCServiceClient is the client API for CDCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CDC Service — gRPC API for the CDC system.
type CDCServiceClient interface {
	// Health & Metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*GetDashboardSummaryResponse, error)
	// Sources CRUD + Test
	CreateSource(ctx context.Context, in *CreateSourceRequest, opts ...grpc.CallOption) (*CreateSourceResponse, error)
	GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error)
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error)
	TestSourceConnection(ctx context.Context, in *TestSourceConnectionRequest, opts ...grpc.CallOption) (*TestSourceConnectionResponse, error)
	// Sinks CRUD + Test
	CreateSink(ctx context.Context, in *CreateSinkRequest, opts ...grpc.CallOption) (*CreateSinkResponse, error)
	GetSink(ctx context.Context, in *GetSinkRequest, opts ...grpc.CallOption) (*GetSinkResponse, error)
	ListSinks(ctx context.Context, in *ListSinksRequest, opts ...grpc.CallOption) (*ListSinksResponse, error)
	DeleteSink(ctx context.Context, in *DeleteSinkRequest, opts ...grpc.CallOption) (*DeleteSinkResponse, error)
	TestSinkConnection(ctx context.Context, in *TestSinkConnectionRequest, opts ...grpc.CallOption) (*TestSinkConnectionResponse, error)
	// Flows CRUD + Lifecycle
	CreateFlow(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error)
	GetFlow(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error)
	ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error)
	UpdateFlow(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error)
	DeleteFlow(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error)
	PauseFlow(ctx context.Context, in *PauseFlowRequest, opts ...grpc.CallOption) (*PauseFlowResponse, error)
	ResumeFlow(ctx context.Context, in *ResumeFlowRequest, opts ...grpc.CallOption) (*ResumeFlowResponse, error)
	GetFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (*GetFlowStatsResponse, error)
	// Discovery
	DiscoverTables(ctx context.Context, in *DiscoverTablesRequest, opts ...grpc.CallOption) (*DiscoverTablesResponse, error)
	DiscoverSinkTables(ctx context.Context, in *DiscoverSinkTablesRequest, opts ...grpc.CallOption) (*DiscoverSinkTablesResponse, error)
	// Explorer API
	GetExplorerOverview(ctx context.Context, in *GetExplorerOverviewRequest, opts ...grpc.CallOption) (*GetExplorerOverviewResponse, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	GetTopicDetail(ctx context.Context, in *GetTopicDetailRequest, opts ...grpc.CallOption) (*GetTopicDetailResponse, error)
	GetPartitionDetail(ctx context.Context, in *GetPartitionDetailRequest, opts ...grpc.CallOption) (*GetPartitionDetailResponse, error)
	ListPartitionMessages(ctx context.Context, in *ListPartitionMessagesRequest, opts ...grpc.CallOption) (*ListPartitionMessagesResponse, error)
	GetMessageDetail(ctx context.Context, in *GetMessageDetailRequest, opts ...grpc.CallOption) (*GetMessageDetailResponse, error)
	GetConsumerInfo(ctx context.Context, in *GetConsumerInfoRequest, opts ...grpc.CallOption) (*GetConsumerInfoResponse, error)
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
	GetConsumerDetail(ctx context.Context, in *GetConsumerDetailRequest, opts ...grpc.CallOption) (*GetConsumerDetailResponse, error)
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error)
	// DLQ
	ListDLQMessages(ctx context.Context, in *ListDLQMessagesRequest, opts ...grpc.CallOption) (*ListDLQMessagesResponse, error)
	PreviewDLQReprocess(ctx context.Context, in *PreviewDLQReprocessRequest, opts ...grpc.CallOption) (*PreviewDLQReprocessResponse, error)
	ReprocessDLQ(ctx context.Context, in *ReprocessDLQRequest, opts ...grpc.CallOption) (*ReprocessDLQResponse, error)
}

type cDCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCDCServiceClient(cc grpc.ClientConnInterface) CDCServiceClient {
	return &cDCServiceClient{cc}
}

func (c *cDCServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CDCService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, CDCService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*GetDashboardSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardSummaryResponse)
	err := c.cc.Invoke(ctx, CDCService_GetDashboardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) CreateSource(ctx context.Context, in *CreateSourceRequest, opts ...grpc.CallOption) (*CreateSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSourceResponse)
	err := c.cc.Invoke(ctx, CDCService_CreateSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSourceResponse)
	err := c.cc.Invoke(ctx, CDCService_GetSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, CDCService_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSourceResponse)
	err := c.cc.Invoke(ctx, CDCService_DeleteSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) TestSourceConnection(ctx context.Context, in *TestSourceConnectionRequest, opts ...grpc.CallOption) (*TestSourceConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestSourceConnectionResponse)
	err := c.cc.Invoke(ctx, CDCService_TestSourceConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) CreateSink(ctx context.Context, in *CreateSinkRequest, opts ...grpc.CallOption) (*CreateSinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSinkResponse)
	err := c.cc.Invoke(ctx, CDCService_CreateSink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetSink(ctx context.Context, in *GetSinkRequest, opts ...grpc.CallOption) (*GetSinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSinkResponse)
	err := c.cc.Invoke(ctx, CDCService_GetSink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListSinks(ctx context.Context, in *ListSinksRequest, opts ...grpc.CallOption) (*ListSinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSinksResponse)
	err := c.cc.Invoke(ctx, CDCService_ListSinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) DeleteSink(ctx context.Context, in *DeleteSinkRequest, opts ...grpc.CallOption) (*DeleteSinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSinkResponse)
	err := c.cc.Invoke(ctx, CDCService_DeleteSink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) TestSinkConnection(ctx context.Context, in *TestSinkConnectionRequest, opts ...grpc.CallOption) (*TestSinkConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestSinkConnectionResponse)
	err := c.cc.Invoke(ctx, CDCService_TestSinkConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) CreateFlow(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_CreateFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetFlow(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_GetFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*ListFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlowsResponse)
	err := c.cc.Invoke(ctx, CDCService_ListFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) UpdateFlow(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_UpdateFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) DeleteFlow(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_DeleteFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) PauseFlow(ctx context.Context, in *PauseFlowRequest, opts ...grpc.CallOption) (*PauseFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_PauseFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ResumeFlow(ctx context.Context, in *ResumeFlowRequest, opts ...grpc.CallOption) (*ResumeFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeFlowResponse)
	err := c.cc.Invoke(ctx, CDCService_ResumeFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (*GetFlowStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlowStatsResponse)
	err := c.cc.Invoke(ctx, CDCService_GetFlowStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) DiscoverTables(ctx context.Context, in *DiscoverTablesRequest, opts ...grpc.CallOption) (*DiscoverTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverTablesResponse)
	err := c.cc.Invoke(ctx, CDCService_DiscoverTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) DiscoverSinkTables(ctx context.Context, in *DiscoverSinkTablesRequest, opts ...grpc.CallOption) (*DiscoverSinkTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverSinkTablesResponse)
	err := c.cc.Invoke(ctx, CDCService_DiscoverSinkTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetExplorerOverview(ctx context.Context, in *GetExplorerOverviewRequest, opts ...grpc.CallOption) (*GetExplorerOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExplorerOverviewResponse)
	err := c.cc.Invoke(ctx, CDCService_GetExplorerOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, CDCService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetTopicDetail(ctx context.Context, in *GetTopicDetailRequest, opts ...grpc.CallOption) (*GetTopicDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicDetailResponse)
	err := c.cc.Invoke(ctx, CDCService_GetTopicDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetPartitionDetail(ctx context.Context, in *GetPartitionDetailRequest, opts ...grpc.CallOption) (*GetPartitionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartitionDetailResponse)
	err := c.cc.Invoke(ctx, CDCService_GetPartitionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListPartitionMessages(ctx context.Context, in *ListPartitionMessagesRequest, opts ...grpc.CallOption) (*ListPartitionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartitionMessagesResponse)
	err := c.cc.Invoke(ctx, CDCService_ListPartitionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetMessageDetail(ctx context.Context, in *GetMessageDetailRequest, opts ...grpc.CallOption) (*GetMessageDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageDetailResponse)
	err := c.cc.Invoke(ctx, CDCService_GetMessageDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetConsumerInfo(ctx context.Context, in *GetConsumerInfoRequest, opts ...grpc.CallOption) (*GetConsumerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsumerInfoResponse)
	err := c.cc.Invoke(ctx, CDCService_GetConsumerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, CDCService_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) GetConsumerDetail(ctx context.Context, in *GetConsumerDetailRequest, opts ...grpc.CallOption) (*GetConsumerDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsumerDetailResponse)
	err := c.cc.Invoke(ctx, CDCService_GetConsumerDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, CDCService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListPartitions(ctx context.Context, in *ListPartitionsRequest, opts ...grpc.CallOption) (*ListPartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartitionsResponse)
	err := c.cc.Invoke(ctx, CDCService_ListPartitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ListDLQMessages(ctx context.Context, in *ListDLQMessagesRequest, opts ...grpc.CallOption) (*ListDLQMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDLQMessagesResponse)
	err := c.cc.Invoke(ctx, CDCService_ListDLQMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) PreviewDLQReprocess(ctx context.Context, in *PreviewDLQReprocessRequest, opts ...grpc.CallOption) (*PreviewDLQReprocessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewDLQReprocessResponse)
	err := c.cc.Invoke(ctx, CDCService_PreviewDLQReprocess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDCServiceClient) ReprocessDLQ(ctx context.Context, in *ReprocessDLQRequest, opts ...grpc.CallOption) (*ReprocessDLQResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReprocessDLQResponse)
	err := c.cc.Invoke(ctx, CDCService_ReprocessDLQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDCServiceServer is the server API for CDCService service.
// All implementations should embed UnimplementedCDCServiceServer
// for forward compatibility.
//
// CDC Service — gRPC API for the CDC system.
type CDCServiceServer interface {
	// Health & Metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*GetDashboardSummaryResponse, error)
	// Sources CRUD + Test
	CreateSource(context.Context, *CreateSourceRequest) (*CreateSourceResponse, error)
	GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error)
	ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error)
	DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error)
	TestSourceConnection(context.Context, *TestSourceConnectionRequest) (*TestSourceConnectionResponse, error)
	// Sinks CRUD + Test
	CreateSink(context.Context, *CreateSinkRequest) (*CreateSinkResponse, error)
	GetSink(context.Context, *GetSinkRequest) (*GetSinkResponse, error)
	ListSinks(context.Context, *ListSinksRequest) (*ListSinksResponse, error)
	DeleteSink(context.Context, *DeleteSinkRequest) (*DeleteSinkResponse, error)
	TestSinkConnection(context.Context, *TestSinkConnectionRequest) (*TestSinkConnectionResponse, error)
	// Flows CRUD + Lifecycle
	CreateFlow(context.Context, *CreateFlowRequest) (*CreateFlowResponse, error)
	GetFlow(context.Context, *GetFlowRequest) (*GetFlowResponse, error)
	ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error)
	UpdateFlow(context.Context, *UpdateFlowRequest) (*UpdateFlowResponse, error)
	DeleteFlow(context.Context, *DeleteFlowRequest) (*DeleteFlowResponse, error)
	PauseFlow(context.Context, *PauseFlowRequest) (*PauseFlowResponse, error)
	ResumeFlow(context.Context, *ResumeFlowRequest) (*ResumeFlowResponse, error)
	GetFlowStats(context.Context, *GetFlowStatsRequest) (*GetFlowStatsResponse, error)
	// Discovery
	DiscoverTables(context.Context, *DiscoverTablesRequest) (*DiscoverTablesResponse, error)
	DiscoverSinkTables(context.Context, *DiscoverSinkTablesRequest) (*DiscoverSinkTablesResponse, error)
	// Explorer API
	GetExplorerOverview(context.Context, *GetExplorerOverviewRequest) (*GetExplorerOverviewResponse, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	GetTopicDetail(context.Context, *GetTopicDetailRequest) (*GetTopicDetailResponse, error)
	GetPartitionDetail(context.Context, *GetPartitionDetailRequest) (*GetPartitionDetailResponse, error)
	ListPartitionMessages(context.Context, *ListPartitionMessagesRequest) (*ListPartitionMessagesResponse, error)
	GetMessageDetail(context.Context, *GetMessageDetailRequest) (*GetMessageDetailResponse, error)
	GetConsumerInfo(context.Context, *GetConsumerInfoRequest) (*GetConsumerInfoResponse, error)
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	GetConsumerDetail(context.Context, *GetConsumerDetailRequest) (*GetConsumerDetailResponse, error)
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error)
	// DLQ
	ListDLQMessages(context.Context, *ListDLQMessagesRequest) (*ListDLQMessagesResponse, error)
	PreviewDLQReprocess(context.Context, *PreviewDLQReprocessRequest) (*PreviewDLQReprocessResponse, error)
	ReprocessDLQ(context.Context, *ReprocessDLQRequest) (*ReprocessDLQResponse, error)
}

// UnimplementedCDCServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCDCServiceServer struct{}

func (UnimplementedCDCServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCDCServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCDCServiceServer) GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*GetDashboardSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedCDCServiceServer) CreateSource(context.Context, *CreateSourceRequest) (*CreateSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSource not implemented")
}
func (UnimplementedCDCServiceServer) GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedCDCServiceServer) ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedCDCServiceServer) DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}
func (UnimplementedCDCServiceServer) TestSourceConnection(context.Context, *TestSourceConnectionRequest) (*TestSourceConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestSourceConnection not implemented")
}
func (UnimplementedCDCServiceServer) CreateSink(context.Context, *CreateSinkRequest) (*CreateSinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSink not implemented")
}
func (UnimplementedCDCServiceServer) GetSink(context.Context, *GetSinkRequest) (*GetSinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSink not implemented")
}
func (UnimplementedCDCServiceServer) ListSinks(context.Context, *ListSinksRequest) (*ListSinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSinks not implemented")
}
func (UnimplementedCDCServiceServer) DeleteSink(context.Context, *DeleteSinkRequest) (*DeleteSinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSink not implemented")
}
func (UnimplementedCDCServiceServer) TestSinkConnection(context.Context, *TestSinkConnectionRequest) (*TestSinkConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestSinkConnection not implemented")
}
func (UnimplementedCDCServiceServer) CreateFlow(context.Context, *CreateFlowRequest) (*CreateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlow not implemented")
}
func (UnimplementedCDCServiceServer) GetFlow(context.Context, *GetFlowRequest) (*GetFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlow not implemented")
}
func (UnimplementedCDCServiceServer) ListFlows(context.Context, *ListFlowsRequest) (*ListFlowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlows not implemented")
}
func (UnimplementedCDCServiceServer) UpdateFlow(context.Context, *UpdateFlowRequest) (*UpdateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlow not implemented")
}
func (UnimplementedCDCServiceServer) DeleteFlow(context.Context, *DeleteFlowRequest) (*DeleteFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFlow not implemented")
}
func (UnimplementedCDCServiceServer) PauseFlow(context.Context, *PauseFlowRequest) (*PauseFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseFlow not implemented")
}
func (UnimplementedCDCServiceServer) ResumeFlow(context.Context, *ResumeFlowRequest) (*ResumeFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeFlow not implemented")
}
func (UnimplementedCDCServiceServer) GetFlowStats(context.Context, *GetFlowStatsRequest) (*GetFlowStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowStats not implemented")
}
func (UnimplementedCDCServiceServer) DiscoverTables(context.Context, *DiscoverTablesRequest) (*DiscoverTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverTables not implemented")
}
func (UnimplementedCDCServiceServer) DiscoverSinkTables(context.Context, *DiscoverSinkTablesRequest) (*DiscoverSinkTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverSinkTables not implemented")
}
func (UnimplementedCDCServiceServer) GetExplorerOverview(context.Context, *GetExplorerOverviewRequest) (*GetExplorerOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExplorerOverview not implemented")
}
func (UnimplementedCDCServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedCDCServiceServer) GetTopicDetail(context.Context, *GetTopicDetailRequest) (*GetTopicDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicDetail not implemented")
}
func (UnimplementedCDCServiceServer) GetPartitionDetail(context.Context, *GetPartitionDetailRequest) (*GetPartitionDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartitionDetail not implemented")
}
func (UnimplementedCDCServiceServer) ListPartitionMessages(context.Context, *ListPartitionMessagesRequest) (*ListPartitionMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPartitionMessages not implemented")
}
func (UnimplementedCDCServiceServer) GetMessageDetail(context.Context, *GetMessageDetailRequest) (*GetMessageDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageDetail not implemented")
}
func (UnimplementedCDCServiceServer) GetConsumerInfo(context.Context, *GetConsumerInfoRequest) (*GetConsumerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerInfo not implemented")
}
func (UnimplementedCDCServiceServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedCDCServiceServer) GetConsumerDetail(context.Context, *GetConsumerDetailRequest) (*GetConsumerDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerDetail not implemented")
}
func (UnimplementedCDCServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedCDCServiceServer) ListPartitions(context.Context, *ListPartitionsRequest) (*ListPartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPartitions not implemented")
}
func (UnimplementedCDCServiceServer) ListDLQMessages(context.Context, *ListDLQMessagesRequest) (*ListDLQMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDLQMessages not implemented")
}
func (UnimplementedCDCServiceServer) PreviewDLQReprocess(context.Context, *PreviewDLQReprocessRequest) (*PreviewDLQReprocessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewDLQReprocess not implemented")
}
func (UnimplementedCDCServiceServer) ReprocessDLQ(context.Context, *ReprocessDLQRequest) (*ReprocessDLQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReprocessDLQ not implemented")
}
func (UnimplementedCDCServiceServer) testEmbeddedByValue() {}

// UnsafeCDCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CDCServiceServer will
// result in compilation errors.
type UnsafeCDCServiceServer interface {
	mustEmbedUnimplementedCDCServiceServer()
}

func RegisterCDCServiceServer(s grpc.ServiceRegistrar, srv CDCServiceServer) {
	// If the following call pancis, it indicates UnimplementedCDCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CDCService_ServiceDesc, srv)
}

func _CDCService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetDashboardSummary(ctx, req.(*GetDashboardSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_CreateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).CreateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_CreateSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).CreateSource(ctx, req.(*CreateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetSource(ctx, req.(*GetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_DeleteSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).DeleteSource(ctx, req.(*DeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_TestSourceConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestSourceConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).TestSourceConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_TestSourceConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).TestSourceConnection(ctx, req.(*TestSourceConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_CreateSink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).CreateSink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_CreateSink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).CreateSink(ctx, req.(*CreateSinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetSink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetSink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetSink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetSink(ctx, req.(*GetSinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListSinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListSinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListSinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListSinks(ctx, req.(*ListSinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_DeleteSink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).DeleteSink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_DeleteSink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).DeleteSink(ctx, req.(*DeleteSinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_TestSinkConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestSinkConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).TestSinkConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_TestSinkConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).TestSinkConnection(ctx, req.(*TestSinkConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_CreateFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).CreateFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_CreateFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).CreateFlow(ctx, req.(*CreateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetFlow(ctx, req.(*GetFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListFlows(ctx, req.(*ListFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_UpdateFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).UpdateFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_UpdateFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).UpdateFlow(ctx, req.(*UpdateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_DeleteFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).DeleteFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_DeleteFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).DeleteFlow(ctx, req.(*DeleteFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_PauseFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).PauseFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_PauseFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).PauseFlow(ctx, req.(*PauseFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ResumeFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ResumeFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ResumeFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ResumeFlow(ctx, req.(*ResumeFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetFlowStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetFlowStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetFlowStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetFlowStats(ctx, req.(*GetFlowStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_DiscoverTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).DiscoverTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_DiscoverTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).DiscoverTables(ctx, req.(*DiscoverTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_DiscoverSinkTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverSinkTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).DiscoverSinkTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_DiscoverSinkTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).DiscoverSinkTables(ctx, req.(*DiscoverSinkTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetExplorerOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExplorerOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetExplorerOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetExplorerOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetExplorerOverview(ctx, req.(*GetExplorerOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetTopicDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetTopicDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetTopicDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetTopicDetail(ctx, req.(*GetTopicDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetPartitionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetPartitionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetPartitionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetPartitionDetail(ctx, req.(*GetPartitionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListPartitionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartitionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListPartitionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListPartitionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListPartitionMessages(ctx, req.(*ListPartitionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetMessageDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetMessageDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetMessageDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetMessageDetail(ctx, req.(*GetMessageDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetConsumerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetConsumerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetConsumerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetConsumerInfo(ctx, req.(*GetConsumerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_GetConsumerDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).GetConsumerDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_GetConsumerDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).GetConsumerDetail(ctx, req.(*GetConsumerDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListPartitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListPartitions(ctx, req.(*ListPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ListDLQMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDLQMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ListDLQMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ListDLQMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ListDLQMessages(ctx, req.(*ListDLQMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_PreviewDLQReprocess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewDLQReprocessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).PreviewDLQReprocess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_PreviewDLQReprocess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).PreviewDLQReprocess(ctx, req.(*PreviewDLQReprocessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDCService_ReprocessDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprocessDLQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDCServiceServer).ReprocessDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDCService_ReprocessDLQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDCServiceServer).ReprocessDLQ(ctx, req.(*ReprocessDLQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CDCService_ServiceDesc is the grpc.ServiceDesc for CDCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CDCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdc.v1.CDCService",
	HandlerType: (*CDCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _CDCService_HealthCheck_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CDCService_GetStats_Handler,
		},
		{
			MethodName: "GetDashboardSummary",
			Handler:    _CDCService_GetDashboardSummary_Handler,
		},
		{
			MethodName: "CreateSource",
			Handler:    _CDCService_CreateSource_Handler,
		},
		{
			MethodName: "GetSource",
			Handler:    _CDCService_GetSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _CDCService_ListSources_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _CDCService_DeleteSource_Handler,
		},
		{
			MethodName: "TestSourceConnection",
			Handler:    _CDCService_TestSourceConnection_Handler,
		},
		{
			MethodName: "CreateSink",
			Handler:    _CDCService_CreateSink_Handler,
		},
		{
			MethodName: "GetSink",
			Handler:    _CDCService_GetSink_Handler,
		},
		{
			MethodName: "ListSinks",
			Handler:    _CDCService_ListSinks_Handler,
		},
		{
			MethodName: "DeleteSink",
			Handler:    _CDCService_DeleteSink_Handler,
		},
		{
			MethodName: "TestSinkConnection",
			Handler:    _CDCService_TestSinkConnection_Handler,
		},
		{
			MethodName: "CreateFlow",
			Handler:    _CDCService_CreateFlow_Handler,
		},
		{
			MethodName: "GetFlow",
			Handler:    _CDCService_GetFlow_Handler,
		},
		{
			MethodName: "ListFlows",
			Handler:    _CDCService_ListFlows_Handler,
		},
		{
			MethodName: "UpdateFlow",
			Handler:    _CDCService_UpdateFlow_Handler,
		},
		{
			MethodName: "DeleteFlow",
			Handler:    _CDCService_DeleteFlow_Handler,
		},
		{
			MethodName: "PauseFlow",
			Handler:    _CDCService_PauseFlow_Handler,
		},
		{
			MethodName: "ResumeFlow",
			Handler:    _CDCService_ResumeFlow_Handler,
		},
		{
			MethodName: "GetFlowStats",
			Handler:    _CDCService_GetFlowStats_Handler,
		},
		{
			MethodName: "DiscoverTables",
			Handler:    _CDCService_DiscoverTables_Handler,
		},
		{
			MethodName: "DiscoverSinkTables",
			Handler:    _CDCService_DiscoverSinkTables_Handler,
		},
		{
			MethodName: "GetExplorerOverview",
			Handler:    _CDCService_GetExplorerOverview_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _CDCService_ListMessages_Handler,
		},
		{
			MethodName: "GetTopicDetail",
			Handler:    _CDCService_GetTopicDetail_Handler,
		},
		{
			MethodName: "GetPartitionDetail",
			Handler:    _CDCService_GetPartitionDetail_Handler,
		},
		{
			MethodName: "ListPartitionMessages",
			Handler:    _CDCService_ListPartitionMessages_Handler,
		},
		{
			MethodName: "GetMessageDetail",
			Handler:    _CDCService_GetMessageDetail_Handler,
		},
		{
			MethodName: "GetConsumerInfo",
			Handler:    _CDCService_GetConsumerInfo_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _CDCService_ListConsumers_Handler,
		},
		{
			MethodName: "GetConsumerDetail",
			Handler:    _CDCService_GetConsumerDetail_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _CDCService_ListTopics_Handler,
		},
		{
			MethodName: "ListPartitions",
			Handler:    _CDCService_ListPartitions_Handler,
		},
		{
			MethodName: "ListDLQMessages",
			Handler:    _CDCService_ListDLQMessages_Handler,
		},
		{
			MethodName: "PreviewDLQReprocess",
			Handler:    _CDCService_PreviewDLQReprocess_Handler,
		},
		{
			MethodName: "ReprocessDLQ",
			Handler:    _CDCService_ReprocessDLQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
