// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sink.proto

package cdcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for a CDC sink connector.
// Connection-level fields only — no topic routing, field mappings, or CEL transformations.
type SinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Host          *string                `protobuf:"bytes,2,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Port          *int32                 `protobuf:"varint,3,opt,name=port,proto3,oneof" json:"port,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Database      *string                `protobuf:"bytes,6,opt,name=database,proto3,oneof" json:"database,omitempty"`
	InstanceId    string                 `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name          *string                `protobuf:"bytes,8,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Url           []string               `protobuf:"bytes,9,rep,name=url,proto3" json:"url,omitempty"`
	ApiKey        *string                `protobuf:"bytes,10,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`
	IndexPrefix   *string                `protobuf:"bytes,11,opt,name=index_prefix,json=indexPrefix,proto3,oneof" json:"index_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkConfig) Reset() {
	*x = SinkConfig{}
	mi := &file_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkConfig) ProtoMessage() {}

func (x *SinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkConfig.ProtoReflect.Descriptor instead.
func (*SinkConfig) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{0}
}

func (x *SinkConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SinkConfig) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *SinkConfig) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *SinkConfig) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *SinkConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SinkConfig) GetDatabase() string {
	if x != nil && x.Database != nil {
		return *x.Database
	}
	return ""
}

func (x *SinkConfig) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SinkConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SinkConfig) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *SinkConfig) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *SinkConfig) GetIndexPrefix() string {
	if x != nil && x.IndexPrefix != nil {
		return *x.IndexPrefix
	}
	return ""
}

// Request to create a new sink.
type CreateSinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sink          *SinkConfig            `protobuf:"bytes,1,opt,name=sink,proto3" json:"sink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSinkRequest) Reset() {
	*x = CreateSinkRequest{}
	mi := &file_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSinkRequest) ProtoMessage() {}

func (x *CreateSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSinkRequest.ProtoReflect.Descriptor instead.
func (*CreateSinkRequest) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSinkRequest) GetSink() *SinkConfig {
	if x != nil {
		return x.Sink
	}
	return nil
}

// Response after creating a sink.
type CreateSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSinkResponse) Reset() {
	*x = CreateSinkResponse{}
	mi := &file_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSinkResponse) ProtoMessage() {}

func (x *CreateSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSinkResponse.ProtoReflect.Descriptor instead.
func (*CreateSinkResponse) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSinkResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Request to get a sink by instance_id.
type GetSinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSinkRequest) Reset() {
	*x = GetSinkRequest{}
	mi := &file_sink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSinkRequest) ProtoMessage() {}

func (x *GetSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSinkRequest.ProtoReflect.Descriptor instead.
func (*GetSinkRequest) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{3}
}

func (x *GetSinkRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Response containing a sink configuration.
type GetSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sink          *SinkConfig            `protobuf:"bytes,1,opt,name=sink,proto3" json:"sink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSinkResponse) Reset() {
	*x = GetSinkResponse{}
	mi := &file_sink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSinkResponse) ProtoMessage() {}

func (x *GetSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSinkResponse.ProtoReflect.Descriptor instead.
func (*GetSinkResponse) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{4}
}

func (x *GetSinkResponse) GetSink() *SinkConfig {
	if x != nil {
		return x.Sink
	}
	return nil
}

// Request to list all sinks.
type ListSinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSinksRequest) Reset() {
	*x = ListSinksRequest{}
	mi := &file_sink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSinksRequest) ProtoMessage() {}

func (x *ListSinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSinksRequest.ProtoReflect.Descriptor instead.
func (*ListSinksRequest) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{5}
}

// Response containing all sink configurations.
type ListSinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sinks         []*SinkConfig          `protobuf:"bytes,1,rep,name=sinks,proto3" json:"sinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSinksResponse) Reset() {
	*x = ListSinksResponse{}
	mi := &file_sink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSinksResponse) ProtoMessage() {}

func (x *ListSinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSinksResponse.ProtoReflect.Descriptor instead.
func (*ListSinksResponse) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{6}
}

func (x *ListSinksResponse) GetSinks() []*SinkConfig {
	if x != nil {
		return x.Sinks
	}
	return nil
}

// Request to delete an existing sink.
type DeleteSinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSinkRequest) Reset() {
	*x = DeleteSinkRequest{}
	mi := &file_sink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSinkRequest) ProtoMessage() {}

func (x *DeleteSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteSinkRequest) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSinkRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Response after deleting a sink.
type DeleteSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSinkResponse) Reset() {
	*x = DeleteSinkResponse{}
	mi := &file_sink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSinkResponse) ProtoMessage() {}

func (x *DeleteSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteSinkResponse) Descriptor() ([]byte, []int) {
	return file_sink_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sink_proto protoreflect.FileDescriptor

const file_sink_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sink.proto\x12\x06cdc.v1\"\xa6\x03\n" +
	"\n" +
	"SinkConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\x04host\x18\x02 \x01(\tH\x00R\x04host\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x03 \x01(\x05H\x01R\x04port\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01\x12\x1f\n" +
	"\bdatabase\x18\x06 \x01(\tH\x04R\bdatabase\x88\x01\x01\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\x04name\x18\b \x01(\tH\x05R\x04name\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\t \x03(\tR\x03url\x12\x1c\n" +
	"\aapi_key\x18\n" +
	" \x01(\tH\x06R\x06apiKey\x88\x01\x01\x12&\n" +
	"\findex_prefix\x18\v \x01(\tH\aR\vindexPrefix\x88\x01\x01B\a\n" +
	"\x05_hostB\a\n" +
	"\x05_portB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\v\n" +
	"\t_databaseB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_api_keyB\x0f\n" +
	"\r_index_prefix\";\n" +
	"\x11CreateSinkRequest\x12&\n" +
	"\x04sink\x18\x01 \x01(\v2\x12.cdc.v1.SinkConfigR\x04sink\"5\n" +
	"\x12CreateSinkResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"1\n" +
	"\x0eGetSinkRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"9\n" +
	"\x0fGetSinkResponse\x12&\n" +
	"\x04sink\x18\x01 \x01(\v2\x12.cdc.v1.SinkConfigR\x04sink\"\x12\n" +
	"\x10ListSinksRequest\"=\n" +
	"\x11ListSinksResponse\x12(\n" +
	"\x05sinks\x18\x01 \x03(\v2\x12.cdc.v1.SinkConfigR\x05sinks\"4\n" +
	"\x11DeleteSinkRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\".\n" +
	"\x12DeleteSinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB)Z'github.com/foden/cdc/api/proto/v1;cdcpbb\x06proto3"

var (
	file_sink_proto_rawDescOnce sync.Once
	file_sink_proto_rawDescData []byte
)

func file_sink_proto_rawDescGZIP() []byte {
	file_sink_proto_rawDescOnce.Do(func() {
		file_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sink_proto_rawDesc), len(file_sink_proto_rawDesc)))
	})
	return file_sink_proto_rawDescData
}

var file_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sink_proto_goTypes = []any{
	(*SinkConfig)(nil),         // 0: cdc.v1.SinkConfig
	(*CreateSinkRequest)(nil),  // 1: cdc.v1.CreateSinkRequest
	(*CreateSinkResponse)(nil), // 2: cdc.v1.CreateSinkResponse
	(*GetSinkRequest)(nil),     // 3: cdc.v1.GetSinkRequest
	(*GetSinkResponse)(nil),    // 4: cdc.v1.GetSinkResponse
	(*ListSinksRequest)(nil),   // 5: cdc.v1.ListSinksRequest
	(*ListSinksResponse)(nil),  // 6: cdc.v1.ListSinksResponse
	(*DeleteSinkRequest)(nil),  // 7: cdc.v1.DeleteSinkRequest
	(*DeleteSinkResponse)(nil), // 8: cdc.v1.DeleteSinkResponse
}
var file_sink_proto_depIdxs = []int32{
	0, // 0: cdc.v1.CreateSinkRequest.sink:type_name -> cdc.v1.SinkConfig
	0, // 1: cdc.v1.GetSinkResponse.sink:type_name -> cdc.v1.SinkConfig
	0, // 2: cdc.v1.ListSinksResponse.sinks:type_name -> cdc.v1.SinkConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sink_proto_init() }
func file_sink_proto_init() {
	if File_sink_proto != nil {
		return
	}
	file_sink_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sink_proto_rawDesc), len(file_sink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sink_proto_goTypes,
		DependencyIndexes: file_sink_proto_depIdxs,
		MessageInfos:      file_sink_proto_msgTypes,
	}.Build()
	File_sink_proto = out.File
	file_sink_proto_goTypes = nil
	file_sink_proto_depIdxs = nil
}
